### ISSUE TITLE
Bangor Savings Bank incorrectly being returned as `auth` product type on getAllInstitutions endpoint

### ISSUE THREAD

**Issue by dbarabander** [plaid/plaid-node#100]
Hey,

Bangor Savings Bank ({"type":"ins_101555"}) is being included in the `getAllInstitutions` endpoint with a product query restraint of "auth" which I do not believe it supports. I do not believe it supports this product type because it 1) Does not correctly load in Plaid Link when requiring this auth type and 2) Does not appear in the `searchAllInstitutions` with the same `auth` restraint.

**Comment by zallarak** [comment]
Hey @dbarabander thanks letting us know. Can you try now? I believe it should be fixed.

**Comment by dbarabander** [comment]
@zallarak it's now showing up on my search, and the login screen is correctly loading via Link, but I am unable to a actually sign in with Username: plaid_test, 
![simulator screen shot feb 10 2017 12 32 05 am](https://cloud.githubusercontent.com/assets/7429159/22815300/80f04166-ef28-11e6-8190-ba51ff028b72.png)

**Comment by michaelckelly** [comment]
@dbarabander - This should be resolved now, please re-open if needed!
