### ISSUE TITLE
A changelog or upgrade guide would be nice for large API changes

### ISSUE THREAD

**Issue by dwolfand** [plaid/plaid-node#105]
Based on the blog post (and our breaking build) it seems like 2.0 was a relatively large change however we can't seem to find any upgrade guide or changelog to help us understand what we need to do specifically to upgrade to 2.0. Is this just buried somewhere and we missed it?

**Comment by dwolfand** [comment]
Just found the transition guide added to the legacy docs, this was very difficult to find, maybe adding a note about it to the readme would be helpful!

**Comment by michaelckelly** [comment]
@dwolfand - Thanks for the feedback. If you didn't see it, that means we can make it clearer -- I'll do so shortly!
