### ISSUE TITLE
Support for createItem, MFA, patchItem

### ISSUE THREAD

**Issue by blwinters** [plaid/plaid-node#107]
In the documentation for Methods, I don't see any that accept credentials for creating/patching items. However in the section on Promise Support, there is the following:

`const promise = plaidClient.createItem(credentials, institutionId, products);`

Does this library and the 2.0 API support manual management of Items by passing in the raw credentials, or must we use Link to accomplish these tasks?

**Comment by michaelckelly** [comment]
@blwinters - The API is meant to work by default with Link, though you can transition an existing direct integration to the new API. Check out the library's integration tests for example code around those areas.
