### ISSUE TITLE
Testing MFA against sandbox credentials

### ISSUE THREAD

**Issue by favistech** [plaid/plaid-node#108]
Hello,

I'm trying to trigger the MFA when creating an item but I always get an INVALID_CREDENTIALS error. I've tried different combinations for the password making sure username is: user_good. I've tried different institutions including the five supported sandbox only institutions. Any suggestions?

> You can trigger any type of MFA flow that Plaid supports when creating an Item. Do so by using username user_good and modifying the password

**Comment by michaelckelly** [comment]
@favistech - Can you confirm that you're using the Sandbox API environment (sandbox.plaid.com)? That's the only environment that supports the test credentials

Try:

```
username: user_good
password: mfa_questions_2_2
```

That will trigger two rounds of MFA questions, where each round will have two questions. See the [sandbox docs](https://plaid.com/docs/api/#sandbox) for complete docs.

**Comment by favistech** [comment]
@michaelckelly confirmed sandbox usage and that password worked and triggered MFA as expected, thank you!
