### ISSUE TITLE
No getIncome function

### ISSUE THREAD

**Issue by RDGthree** [plaid/plaid-node#109]
Hey there! I feel like I'm going crazy right now - there's a getIncome function that's mentioned in the docs, but it's undefined in the client library and I can't find it in the code here. If you switch to node, it's specified in the docs here: https://plaid.com/docs/api/#income

Is this not implemented yet or am I missing something? 

Thanks!

**Comment by michaelckelly** [comment]
Hey @RDGthree - not crazy! That's an oversight on our end. #110 will fix this!

**Comment by RDGthree** [comment]
Awesome! Thank you! Appreciate the quick response.

**Comment by michaelckelly** [comment]
@RDGthree - `getIncome` is included in version 2.0.2, which was just published 👍

**Comment by RDGthree** [comment]
Awesome, thanks again!
