### ISSUE TITLE
Pending transactions for Discover Card

### ISSUE THREAD

**Issue by favistech** [plaid/plaid-node#111]
I'm not getting any pending transactions for my Discover Card account. I've waited 48 hours just to be sure. I wanted to make sure there wasnt any pending flag I need to set for in options in createItem for example. Saw legacy issue #70 so just wanted to be sure if this was also the case for the latest API.

**Comment by michaelckelly** [comment]
@favistech - Pending transactions are always returned, when available, in our current API (head to the [docs](https://plaid.com/docs/api/#transactions) for more). In some cases, pending transactions are not available from the financial institution. That may be the case here.
