### ISSUE TITLE
Unable to exchange public token

### ISSUE THREAD

**Issue by tgrander** [plaid/plaid-node#116]
I have successfully used Link to create items and to retrieve a public token from the item. However, every attempt at plaidClient.exchangePublicToken results in an error. I have made sure that the req.body is correctly populated with the public_token. 

My plaid keys are regular strings. 

The item public_key is correctly passed to the exchangePublicToken function. 

The error is very vague and only states that `Could not exchange public_token!`

What do I seem to be doing wrong?

```javascript
var express = require('express');
var router = express.Router();
var bodyParser = require('body-parser');
var plaid = require('plaid');

// fake keys for this example
var PLAID_CLIENT_ID = '123123123123';
var PLAID_SECRET = '123123123123123';
var PLAID_PUBLIC_KEY = '123123123123123';
var PLAID_ENV = 'development';

// Initialize the Plaid plaidClient
var plaidClient = new plaid.Client(
    PLAID_CLIENT_ID,
    PLAID_SECRET,
    PLAID_PUBLIC_KEY,
    plaid.environments[PLAID_ENV]
);

router.use(bodyParser.json());
router.use(bodyParser.urlencoded({ extended: true }));

router.post('/authenticate_item', function(req, res, next) {
  var accountPublicToken = req.body.public_token;
  plaidClient.exchangePublicToken(accountPublicToken, function(error, tokenResponse) {
    if (error != null) {
        var msg = 'Could not exchange public_token!';
        console.log(msg + '\n' + error);
        return res.json({error: msg});
    }

    var accessToken = tokenResponse.access_token;
    console.log('Access Token: ' + accessToken);

  });
});
```

**Comment by michaelckelly** [comment]
@tgrander - What is the error returned from the `plaidClient.exchangePublicToken` call?

**Comment by tgrander** [comment]
@michaelckelly the error message is as follow: 

```javascript
{ display_message: null,
error_code: ‘INVALID_PUBLIC_TOKEN‘,
error_message: ‘provided public token is in an invalid format. expected format: public-<environment>-<identifier>’,
error_type: ‘INVALID_INPUT‘,
request_id: ‘vVGLl’,
status_code: 400 }
```

The error states that the expected format is `public-<environment>-<identifier>`, which I do not understand. What does identifier refer to?

**Comment by michaelckelly** [comment]
@tgrander - Thanks for sharing that additional context. It looks like you're using Link on the client-side with our [updated API](https://blog.plaid.com/improving-our-api) and then using our [legacy API](https://plaid.com/docs/legacy/api) on the backend.

What `env` have you configured Link to use client side? Since you're using `development` server-side, you'll also want to use `env = development` when initializing Link client-side.
