### ISSUE TITLE
Unhandled TypeError on 503 error

### ISSUE THREAD

**Issue by sofcal** [plaid/plaid-node#121]
Hi,

I was doing some testing against a plaid sandbox the other day and had a 503 response from the server, I didn't inspect the body of the response at the time but my assumption is it wasn't something that parsed to an object. Because of this, the module throws a TypeError "Cannot assign to read only property 'status_code'" but this error doesn't appear to be caught in the promise implementation. 

In plaidRequest.js (line: 77), the following code creates the Promise:
`return wrapPromise(new Promise(function(resolve, reject) {
    request(requestOptions, function(err, res, body) {
      handleApiResponse(resolve, reject, err, res, body,
        requestSpec.includeMfaResponse);
    });
  }), cb);`

but the TypeError occurs at the start of the handleApiResponse function, isn't caught and doesn't reject the Promise. Meaning I can't handle these errors which may occur - I assume it'll be the same for any non-code based responses that don't return an object response.

I've tested this locally using nock (npm module for stubbing http requests), with the following stub:
`nock('https://sandbox.plaid.com)
                .post('/institutions/get', `{\"secret\":\"${secret}\",\"client_id\":\"${client_id}\",\"count\":500,\"offset\":0}`)
                .reply(503, 'oops')`

and then making a request to client.getInstitutions(500, 0)

**Comment by michaelckelly** [comment]
Thanks for flagging this @sofcal

**Comment by sofcal** [comment]
Hi Michael, 

Is there any update on this issue?

**Comment by sofcal** [comment]
Hi again. Is there any update on this issue yet? We're getting close to the point we'd like to release with this module, but potential unhandled exceptions are a cause for concern.

**Comment by michaelckelly** [comment]
@sofcal - thanks for the bump and apologies for the slowness here, prioritizing a fix for this today

**Comment by michaelckelly** [comment]
`plaid@2.0.5` has just been published with this fix

**Comment by sofcal** [comment]
Hi Michael, 

We managed to integrate this a couple week ago, and everything has been working great. Thanks.
