### ISSUE TITLE
Access token error when running quickstart code

### ISSUE THREAD

**Issue by syzhang88** [plaid/plaid-node#125]
Hello, 

I get this error when trying to run the python quickstart code on this github. I also tried running the node version, which returned a 400 INVALID_REQUEST error, with error code INVALID_FIELD. 

Specifically, here is the screenshot when I try to log in using user_good on sandbox mode:
 
<img width="572" alt="screen shot 2017-06-22 at 10 12 00 am" src="https://user-images.githubusercontent.com/8379968/27446739-7ebcbf46-5733-11e7-8ae8-87710628aade.png">

Does anyone know what could be the issue? Aside from adding my api keys, I have not modified the code. I have used pip to install all the relevant packages. 

Thanks!
Sam

**Comment by michaelckelly** [comment]
@syzhang88 - Are you still experiencing this issue with the Node and Python quickstarts -- if so, can you share the API request ID of one of the failed requests? From there we (Plaid) can track down the request in the logs and figure out what went wrong.

**Comment by syzhang88** [comment]
Hello Michael,

Sorry for not responding earlier, but we've fixed the problem. Thanks a lot
for your help!

Best,
Sam


On Jul 24, 2017 10:16 AM, "Michael Kelly" <notifications@github.com> wrote:

@syzhang88 <https://github.com/syzhang88> - Are you still experiencing this
issue with the Node and Python quickstarts -- if so, can you share the API
request ID of one of the failed requests? From there we (Plaid) can track
down the request in the logs and figure out what went wrong.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/plaid/plaid-node/issues/125#issuecomment-317491912>,
or mute
the thread
