### ISSUE TITLE
502 Bad Gateway - crashing our job server

### ISSUE THREAD

**Issue by phaddius** [plaid/plaid-node#135]
This is the same problem as https://github.com/plaid/plaid-python/issues/106

This is crashing our job server since the traditional error catching mechanisms aren't working when an unexpected html file is returned. So requesting a fix for the node client.

**Comment by michaelckelly** [comment]
@phaddius - `2.1.1` is published on npm with the fix from #136

**Comment by phaddius** [comment]
Thanks!
