### ISSUE TITLE
Sandbox Testing - Account ID

### ISSUE THREAD

**Issue by danielchangsoojones** [plaid/plaid-node#164]
I am trying to write some tests for plaid integration with Stripe. I don't want to have to go through the Link user flow every time to get a plaidPublicToken when I am testing. So, I first run this function to get a sandbox plaidPublicKey:

```
plaidClient.sandboxPublicTokenCreate(
        "ins_109511", ['auth'], function(error, response) {
           var plaidPublicToken = response.public_token;
});
```
So, now I have the plaidPublicToken, and I use this plaidPublicToken to create a plaidAccessToken:

```
plaidClient.exchangePublicToken(
        plaidPublicToken, function (error, res) {
        var accessToken = res.access_token;
        var item_id = res.item_id;
    })
```
Now, I need to use this access token to actually tell Stripe to create a stripeBankToken:

```
plaidClient.createStripeToken(plaidAccessToken, accountID, function (error, res) {
        var stripeBankToken = res.stripe_bank_account_token;
});
```

The problem is that I need to pass the createStripeToken function an accountID, but I can't seem to find where the accountID was ever created in any of the above responses. It just returns the error that it can't find the account, which makes sense because I haven't passed it an accountID. My iOS client works because it runs the Link picker, and then it returns the accountID once we select an account. And, it seems to be inside the metadata, but I can't find any metadata within any of these responses. How can I get the accountID when running tests where I don't use Link?

**Comment by michaelckelly** [comment]
@danielchangsoojones - Sorry for the slow response on this one. When a real-user goes through the Link flow, typically developers enable the Select Account view. When that's enabled, the developer gets the account ID that the user selected via the `onSuccess` callback.

Since you're using the `/sandbox/public_token/create` endpoint, there is no real user and no Select Account view. So you'll need to make an `/accounts/get` call and pick an account ID that is either of subtype `checking` or `savings`. Then you should be able to use that account ID to generate the Stripe bank account token.

**Comment by Joycechocho** [comment]
Even I make a call to https://sandbox.plaid.com/accounts/get to get the account Id, the plaidClient.createStripeToken is still throwing an error 
  error_code: 'INVALID_ACCOUNT_ID',
  error_message: 'One or more Account id(s) missing or deleted',

Is there any other way to test the stripe and plaid link in the web view?

**Comment by lsmolic** [comment]
Can someone PLEASE adjust the docs to say something about this. Spent 4 hours today trying to hunt this down and if it were not for the valiant issue creation of @danielchangsoojones, I'd still be looking around.  Just something very clear like "you'll need to make sure you do XXXX in test and here is how you do it ----> {CURL} / Ruby / Python "

This affect all languages. 

Thank you!

**Comment by kevflynn** [comment]
Lol, I'm sorry but how is this still not in the docs????

**Comment by alexboots** [comment]
For anyone else who ends up here, you can set 'Select account' behavior here:
https://dashboard.plaid.com/link/account-select

**Comment by JoshCarterWeb** [comment]
Thank god this thread exists

@michaelckelly Could we get this in the docs, please?

**Comment by khacnha** [comment]
The document is confusing. @.@
Thank god this thread exists

**Comment by dradeng** [comment]
Thanks for creating this thread. Frustrating this is still not in the docs.

**Comment by phoenixy1** [comment]
oh dear!  I believe we missed this one because this issue was closed back in 2018.  I just merged a docs fix for this that should be out in the next day or so.
