### ISSUE TITLE
Reject with errors instead of objects

### ISSUE THREAD

**Issue by ckknight** [plaid/plaid-node#166]
It is incredibly confusing to deal with errors that aren't derived from `Error`. It becomes nigh-impossible to track down where the error originates from and does not work well with the rest of the tooling of the JavaScript ecosystem, particularly loggers.

All errors that are thrown or rejected should either be instantiations of `Error` or an exported, well-known error type that itself derives from `Error`.

**Comment by idris** [comment]
@michaelckelly any chance we can get this fixed?  A lot of error handling, including 3rd party tools, expect thrown errors to be `Error`s, not normal JS objects.

**Comment by michaelckelly** [comment]
Fixed via #175
