### ISSUE TITLE
Difference in AuthResponse interface and actual response

### ISSUE THREAD

**Issue by jmkomala** [plaid/plaid-node#169]
AuthResponse Interface under numbers has ETF but actual response has EFT... 
![image](https://user-images.githubusercontent.com/32344914/44373675-4047c200-a49f-11e8-9ae2-29994830171a.png)

 interface AuthResponse extends BaseResponse {
    accounts: Array<Account>;
    item: Item;
    numbers: {
      ach: Array<ACHNumbers>;
      etf: Array<EFTNumbers>;
    }
  }

Actual : 
{
"accounts": [
"item": {...},
"numbers": {
        "ach": [
            { .... },
        ],
        **"eft"**: [{...}]
    },
"request_id": "...."
}

**Comment by michaelckelly** [comment]
@jmkomala Sorry about the slow follow up here -- you're completely right, this is a bug. #173 will fix.

**Comment by michaelckelly** [comment]
@jmkomala - The fix was published to npm as `2.8.2`
