### ISSUE TITLE
plaidClient.createStripeToken(access_token, account_id, cb);

### ISSUE THREAD

**Issue by clam004** [plaid/plaid-node#176]
`plaidClient.createStripeToken(access_token, account_id, cb);
`
What is account_id ? , I am following these instructions https://stripe.com/docs/ach and there is no mention of how to get the {ACCOUNT_ID} or what it is. Thanks.

**Comment by clam004** [comment]
Sorry my bad, it is in the metadata at metadata.account_id returned onSuccess by PlaidLink

**Comment by aodhgan** [comment]
@ntindall If you are writing integration tests with the sandbox and are not using Link, how do you get this variable?

**Comment by aodhgan** [comment]
The docs dont answer my question but the info in this issue do https://github.com/plaid/plaid-node/issues/164

**Comment by xeroxstar** [comment]
This tutorial is not complete, after this:
```
var plaid = require('plaid');
var plaidClient = new plaid.Client({
    clientID: 'PLAID_CLIENT_ID',
    secret: 'PLAID_SECRET',
    env: plaid.environments.sandbox
});
plaidClient.exchangePublicToken('PUBLIC_TOKEN', function(err, res) {
    var accessToken = res.access_token;
    // Generate a bank account token
    plaidClient.createStripeToken(accessToken, 'ACCOUNT_ID', function(err, res) {
        var bankAccountToken = res.stripe_bank_account_token;
    });
```

How we should charge the client?

**Comment by xeroxstar** [comment]
> This tutorial is not complete, after this:
> 
> ```
> var plaid = require('plaid');
> var plaidClient = new plaid.Client({
>     clientID: 'PLAID_CLIENT_ID',
>     secret: 'PLAID_SECRET',
>     env: plaid.environments.sandbox
> });
> plaidClient.exchangePublicToken('PUBLIC_TOKEN', function(err, res) {
>     var accessToken = res.access_token;
>     // Generate a bank account token
>     plaidClient.createStripeToken(accessToken, 'ACCOUNT_ID', function(err, res) {
>         var bankAccountToken = res.stripe_bank_account_token;
>     });
> ```
> 
> How we should charge the client or what we should do with the **res.stripe_bank_account_token**?

@pbernasconi

**Comment by photoplyr** [comment]
How do I manually create this call createStripeToken, we are not using require('plaid') in our node code?
