### ISSUE TITLE
Add ts types for `include_optional_metadata`

### ISSUE THREAD

**Issue by tonyxiao** [plaid/plaid-node#194]
I saw in the changelog https://github.com/plaid/plaid-node/blob/master/CHANGELOG.md that `include_optional_metadata` and previously `include_display_data` are now supported. However the only way to figure out how to use them was to check the test files. It would be great if this was documented in `index.d.ts`

**Comment by pbernasconi** [comment]
Closing this as done.

We've since added `InstitutionWithInstitutionData` which exposes `primary_color`, `url` and `logo` for institution endpoints that support `include_optional_metadata`.
