### ISSUE TITLE
`plaid_client.sandboxItemFireWebhook` is not passing options to `_authenticatedRequest` properly

### ISSUE THREAD

**Issue by andyburke** [plaid/plaid-node#199]
https://github.com/plaid/plaid-node/blob/master/lib/PlaidClient.js#L391

It appears that this call to `_authenticatedRequest` is missing its `options` argument, so that the `cb` argument ends up being the `true` passed in for `withPublicKey`. This is, at the least, breaking using `await` when calling `.sandboxItemFireWebhook`.

**Comment by skylarmb** [comment]
Hi there @andyburke, this appears to be resolved. `getPaymentRecipient` only takes 2 arguments now, so this should not be an issue anymore.

**Comment by skylarmb** [comment]
Hey there, thanks for this report. It appears this instance of `_authenticatedRequest` is not the only that has this issue.  Ive added this issue to our internal backlog to be prioritized.

**Comment by anjiren** [comment]
Looks like https://github.com/plaid/plaid-node/blob/master/lib/PlaidClient.js#L68 is juggling the arguments to handle this now. Closing out this issue.
