### ISSUE TITLE
Incorrect typings

### ISSUE THREAD

**Issue by tonyxiao** [plaid/plaid-node#207]
According to https://plaid.com/docs/#transactions

![image](https://user-images.githubusercontent.com/696842/59556348-c032a180-8f75-11e9-99eb-2b4ea460a140.png)

However, in types, 
```ts
interface Account extends AccountCommon {
    balances: {
      available: number | null;
      current: number | null;
      limit: number | null;
      iso_currency_code: string | null;
      official_currency_code: string | null;
    };
  }
```

`official_currency_code` should be updated.

**Comment by tonyxiao** [comment]
Similarly, for `ItemResponse`,

```ts
interface ItemResponse {
    /** Emprically exists, but missing in plaid node index.d.ts */
    status: {
      last_webhook: string | null
      transactions: {
        last_failed_update: string
        last_successful_update: string
      }
    }
  }
```

**Comment by ljuvtliv** [comment]
interface Category {
    type: string;
    hierarchy: Array<string>;
    category_id: string;
  }

Is incorrect as the api returns group: instead of type:
Changing type to group fixes it for me.

**Comment by pbernasconi** [comment]
Thanks @ljuvtliv – in the future do you mind opening a separate issue this?

I've created https://github.com/plaid/plaid-node/pull/216 to fix this – will be merged and released shortly

**Comment by ljuvtliv** [comment]
Not at all, I was unsure whether to open a separate ticket.
Glad i could help.
