### ISSUE TITLE
Client Options Interface - Fix primitive type

### ISSUE THREAD

**Issue by travmichwill** [plaid/plaid-node#220]
Excuse my inability to make a merge request(due to issues with "make  setup" on windows.)

In file: index.d.ts, Line 572
```javascript
interface ClientOptions extends CoreOptions {
    version?: string;
    // version?: '2019-05-29';
  }
```

Because of typescript, the interface needs to define the primitive type and not a default value.

**Comment by skylarmb** [comment]
Hi there @travmichwill. Thanks for submitting this. I opened up https://github.com/plaid/plaid-node/pull/239
