### ISSUE TITLE
How do I correctly check if a user has already linked with an institution

### ISSUE THREAD

**Issue by KolbySisk** [plaid/plaid-node#222]
I'm not sure if there's a bug or I'm misunderstanding. 

The docs say:

> access_tokens and item_ids are the core identifiers that map your end-users to their financial institutions

But access_tokens and item_ids are always different in both the `exchangePlaidToken` and the `getLiabilities` responses.

I was expecting either `access_token` or `item_id` to be the same every time I Link with the same institution. That way, when a user links with that institution again, I can check if the Plaid_Item already exists and prevent adding it again.

I can reproduce this by Linking with Navient multiple times. Each time I get a different `access_token` and `item_id`.

**Comment by acarino** [comment]
@KolbySisk this is a common question for developers integrating with the Plaid API, and we attempt to demystify it in Plaid Pattern, our reference implementation.
https://github.com/plaid/pattern/tree/master/server#preventing-item-duplication 
Basically the best practice is to check if a connection to the institution exists for the user before completing the token exchange:
https://github.com/plaid/pattern/blob/master/server/routes/items.js#L42-L49
Plaid Pattern shows how to associate a user to an item to facilitate this type of check.
If you experiment with Pattern, let us know what you think about it, as it was created by developers for developers, and we are always looking to improve it.

**Comment by KolbySisk** [comment]
I see where my confusion stemmed from. 

The docs show, and document, that you send the `public_token` to the server: 

```
onSuccess: function(public_token, metadata) {
      // Send the public_token to your app server.
      // The metadata object contains info about the institution the
      // user selected and the account ID or IDs, if the
      // Select Account view is enabled.
      $.post('/get_access_token', {
        public_token: public_token,
      });
 },
```

In practice though, you need to send the `public_token` and `institution_id ` to the server. Then you can avoid the exchange by checking the `institution_id` against the `user_id`.

I wonder though, if relying on the `institution_id` from the client could have any security/bug concerns. It would be trivial to send a random `institution_id` along with the request. I guess nothing too severe could happen though. Just a thought.

Thanks for clearing that up.

**Comment by skylarmb** [comment]
Hey there @KolbySisk, if you need any further help with this please open a support ticket here: https://dashboard.plaid.com/support/new/product-and-development
