### ISSUE TITLE
getInstitutions typescript definition doesn't have options param

### ISSUE THREAD

**Issue by jabas06** [plaid/plaid-node#226]
`getInstitutions` method within PlaidClient.js already accepts the `options` param, but the typescript definition doesn't

```
Client.prototype.getInstitutions =
  function(count, offset, options, cb) {
    return this._authenticatedRequest({
      path: '/institutions/get',
      body: {
        count: count,
        offset: offset
      },
    }, options, cb);
  };
```
Following error is shown when using typescript:

```Argument of type '{ include_optional_metadata: boolean; }' is not assignable to parameter of type 'Callback<GetInstitutionsResponse<Institution>>'.```

**Comment by skylarmb** [comment]
Hi there, @jabas06 thanks for the report. I’ve added this issue to our internal backlog to be prioritized.

**Comment by davidzhanghp** [comment]
Addressed by @jabas06 here. https://github.com/plaid/plaid-node/pull/252

Thanks!
