### ISSUE TITLE
getHoldings does not allow the account_ids option to be specified

### ISSUE THREAD

**Issue by bodaro** [plaid/plaid-node#230]
The API for investment holdings has an option for account_ids but the node library call `getHoldings` does not take this option.

Ideally, the second parameter for `getHoldings` is the options. If this second parameter is null or {} or does not contain the account_ids property, or that property is the empty array, it should be agnostic to the account. Otherwise the object should retrieve holdings (and related securities) just for the given accounts).

See: https://plaid.com/docs/#investments

**Comment by skylarmb** [comment]
Hey there @bodaro thanks for the report. I’ve added this issue to our internal backlog to be prioritized. Pull requests and +1s on the issue summary will help move it up the backlog.

**Comment by skylarmb** [comment]
hey @bodaro, just going through old low-pri issues here... according to the docs on `options`: "If provided, must be non-null". That rules out the null case. If you are passing an options object, the options object gets passed [directly](https://github.com/plaid/plaid-node/blob/master/lib/PlaidClient.js#L267) [to the](https://github.com/plaid/plaid-node/blob/master/lib/PlaidClient.js#L54) [API](https://github.com/plaid/plaid-node/blob/master/lib/PlaidClient.js#L76) (no validation in this library), which is the same for all endpoints that take options, so passing `account_ids` will work the same as if you were interacting directly with the JSON api.

However, i did notice the typescript type was out of date for this function, so i fixed that here: #312
