### ISSUE TITLE
INVALID_REQUEST

### ISSUE THREAD

**Issue by diana4397** [plaid/plaid-node#231]
Hi, I am getting following error from plaid:
errr { display_message: null,
  error_code: 'INVALID_FIELD',
  error_message: 'public_key must be a properly formatted, non-empty string',
  error_type: 'INVALID_REQUEST',
  request_id: 'OiQnV58jOwa2qbZ',
  suggested_action: null,
  status_code: 400 }

**Comment by daniellacoste** [comment]
Hey @diana4397 - please file a support ticket for us from your [Plaid Dashboard](https://dashboard.plaid.com/support) so that we can help you. Thanks!

**Comment by asna11** [comment]
Hi @diana4397, I have tried to remove public key from "key" property and pass it to the "token" property. It worked for me.
