### ISSUE TITLE
Transactions are sometimes undefined in an asset report

### ISSUE THREAD

**Issue by rclmenezes** [plaid/plaid-node#242]
Hi,

We've been running into production issues where `transactions` in a retrieved asset report is undefined.

Maybe we should update the typing for AssetReport?
https://github.com/plaid/plaid-node/blob/master/index.d.ts#L341

Thanks

**Comment by skylarmb** [comment]
Hi there @rclmenezes. As far as I can tell that field should never be undefined. If you are seeing that behavior in production, could you file a support ticket? Thanks!

Here is the category I would recommend. 
https://dashboard.plaid.com/support/new/product-and-development/product-troubleshooting/product-functionality

**Comment by dguo** [comment]
@skylarmb, we discovered that this was an issue on our side. Sorry for the trouble. Feel free to close this issue.
