### ISSUE TITLE
Option to return keys as camelCase

### ISSUE THREAD

**Issue by jgonera** [plaid/plaid-node#249]
Since camelCase is the dominant naming convention in JS, it would be nice if this library automatically converted snake_case <-> camelCase. While it's easy to write a function that will convert to camelCase in JS, it's not possible to have such a function preserve proper types when using TypeScript.

**Comment by cgfarmer4** [comment]
hi @jgonera- thanks for the feedback. We will take this into account for future releases but do not plan to update to this convention at this time.
