### ISSUE TITLE
Example unclear

### ISSUE THREAD

**Issue by hackley** [plaid/plaid-node#28]
The example provided is very unclear. Who's email is "test@plaid.com"? The user's? Also, the credentials 'demo' and 'test' don't seem to work. After some digging it looks like 'plaid_test' and 'plaid_good' do, though.

```js
plaid.connect({username: 'demo', password: 'test'}, 'type', 'test@plaid.com', function(error, response, mfa){
...
}

```

**Comment by michaelckelly** [comment]
Hi Nathan,

Sorry about the trouble - unfortunately the node module is a bit of date (as you noticed).  Updating the module is absolutely on our minds - keep an eye out for an updated version soon.

The best place to get started with Plaid will be our [docs](plaid.com/docs).  That will be the most up-to-date resource for the API.

**Comment by dazziola** [comment]
Is this module up to date with the newly released Plaid API?

**Comment by whockey** [comment]
hi @dazziola - all seems to be working now. Much of the ambiguity is resolved in https://github.com/plaid/plaid-node/pull/34.
