### ISSUE TITLE
[Question] How do I create custom test accounts?

### ISSUE THREAD

**Issue by jdavis61** [plaid/plaid-node#281]
How do I create custom test accounts, e.g. test items? I have checked the documentation and cannot find this information at all.

I am asking because my company is integrating with plaid and I want to create test accounts that return specific data, e.g. login as user_tdbank, password pass_tdbank. The transactions response returns 30 debit card transactions.

**Comment by otherchen** [comment]
Hey @jdavis61, to do this today, you will have to use the `user_custom` test credentials (https://plaid.com/docs/#custom-sandbox). The custom sandbox should allow you to configure the account and transactions information that you want.

The username will be `user_custom` and the password will be a JSON string of configurations.

**Comment by jdavis61** [comment]
Thanks @otherchen, once I create test data, can this be accessed using the Live modal using user_good / pass_good?
