### ISSUE TITLE
How can I generate a public token for integration tests

### ISSUE THREAD

**Issue by L-u-k-e** [plaid/plaid-node#282]
I have an API endpoint which exchanges a public token (generated via Link in my web app) for an access token and then calls some other apis, puts stuff in a database, etc. I want to write an integration test for this endpoint. How can I generate a public token to do so?

**Comment by davidzhanghp** [comment]
Hi @L-u-k-e,

You can test this in the sandbox environment via `/sandbox/public_token/create`
https://plaid.com/docs/#creating-items-in-the-sandbox

Many of our clients use the sandbox environment to write integration test purposes.

**Comment by davidzhanghp** [comment]
Please let me know if there's anything I can clarify for you. Otherwise please feel free to close this issue.
