### ISSUE TITLE
Wrong definition of getWebhookVerificationKey

### ISSUE THREAD

**Issue by sk-** [plaid/plaid-node#299]
As explained in #293, `getWebhookVerificationKey` does not allow to not pass the callback.

The problem is that you are setting the `withPublicKey` argument, which for this endpoint is not allowed as it needs the secret.

The error raised when calling it with no callback is:

```
Uncaught TypeError: cb is not a function
```

The problem is that in that case you end up calling:

```
plaidRequest(context, requestSpec, this.client_request_opts, cb)
```

but cb in that context is set to true, which triggers the error en `wrapPromise` https://github.com/plaid/plaid-node/blob/master/lib/wrapPromise.js#L10.

With a callback works despite the fact that `withPublicKey` is set to `true`, because there's a bug in `_authenticatedRequest`, which does not set `withPublicKey` when `options` is the callback.

in that case the code should be:

```
if (typeof options === 'function') {
   withPublicKey = cb; // This is the missing line
   cb = options;
   options = {};
} else {
   requestSpec.body.options = options;
}
```

Alternatively the caller could fix it by calling instead:

```
this._authenticatedRequest({
    path: '/webhook_verification_key/get',
    body: {
      key_id: key_id,
    },
  }, undefined, cb, true);
```

Although note that this endpoint requires the secret, so that argument is wrong.

**Comment by sk-** [comment]
@skylarmb could you take a look

**Comment by skylarmb** [comment]
fixed in: https://github.com/plaid/plaid-node/pull/293
