### ISSUE TITLE
Provide OpenAPI definitions

### ISSUE THREAD

**Issue by sk-** [plaid/plaid-node#301]
Is there any chance you could provide OpenApi definitions for the API.

In that way we could generate a full client ourselves using our own http library. Note that that would also help those languages for which you don't provide a client.

Generating our own client, would allow us to successfully manage LIMIT EXCEEDED requests. One could do it with version 5.0, by using axios interceptors, but that would be using an implementation detail, and I think in that case there could be a problem with the dependencies a axios is not a peer dependency.

I think this is important, as currently the client is lacking certain fields (feature is being triaged internally), having errors when using promises, typescript definitions incomplete, etc.

**Comment by skylarmb** [comment]
hey @sk-, great minds think alike. We are actually already working on OpenAPI definitions for our API as part of an ongoing project to auto-generate many things, and as you guessed, API client libraries are one of those things. Hopefully this effort will result in no more issues with missing types like all your recent issues / PRs have been pointing out. When we finish the definition i am sure we would be happy to open source it. Keep an eye open for this in the coming quarters!

**Comment by sk-** [comment]
Is there any chance we could have an earlier preview than in a couple of quarters. The current typings and docs are incomplete, so having a closer to implementation spec file would be much appreciated.

See for example https://github.com/plaid/plaid-node/issues/305

**Comment by phoenixy1** [comment]
So speaking as the person who is probably most actively working on it -- we are actively working on it!  The first draft of the OpenAPI YAML file is almost done, but we still need to kick the tires by testing clib generation from it to make sure it contains everything we need.  I moved this into the Low Priority bucket because this is already on our roadmap and the person who looks through the triage buckets can't do much about it, but rest assured it is happening (and probably sooner than a couple of quarters).

**Comment by c650** [comment]
Hey there! Thanks for all your efforts. How's this coming along? My team is looking to codegen a rust client for the plaid api. :)

**Comment by sk-** [comment]
The README now says:

> The `OpenAPI` file will be actively maintained and published (coming soon - Q1 2021) whenever changes are made to any of our external HTTP API surfaces. `Typescript 4.0`, `Mocha 8.0` and  `Node 14` are now supported.

**Comment by skylarmb** [comment]
hey @sk- @c650 https://github.com/plaid/plaid-OpenAPI
