### ISSUE TITLE
Convert tests to Typescript and test async/await or promises

### ISSUE THREAD

**Issue by skylarmb** [plaid/plaid-node#304]
Most integrations these days are likely to use async/await or promises instead of callbacks, as well as Typescript. Our tests are currently written in JS and use callbacks, which does not reveal issues with using our typescript types and implementation bugs with async/await and promises. 

Not having our own tests test the most common implementations of the library results in many avoidable bugs, such as 

https://github.com/plaid/plaid-node/issues/251
https://github.com/plaid/plaid-node/issues/303
https://github.com/plaid/plaid-node/issues/300
https://github.com/plaid/plaid-node/issues/217
https://github.com/plaid/plaid-node/issues/226

etc, etc

**Comment by cgfarmer4** [comment]
This is done for the current beta release.
