### ISSUE TITLE
Incorrect typings for Institution

### ISSUE THREAD

**Issue by sk-** [plaid/plaid-node#305]
The typings for `InstitutionWithInstitutionData` and `Institution` are incorrect, as the `logo` is marked to be a non-nullable string however the API does return null for certain institutions. For example `ins_54` (note that institution hast quite many users) or `ins_100546 `

See https://github.com/plaid/plaid-node/blob/c899967/index.d.ts#L203

Also, according to https://plaid.com/docs/#institution-schema, all those types are nullable, `logo`, `url` and `primary_color`.

However I do not know which definition to trust, as the docs say the `routing_numbers` is part of the institution, but they do not mention `credentials`, which they are in the TS definition file and are also used in the sample responses.

There are even some other fields returned, that are not even documented anywhere.

**Comment by phoenixy1** [comment]
Yes, apologies for this issue.  The undocumented fields are because we are exposing externally fields that we use internally.  We shouldn't do this and we have a backlog item to address it.  (The typings are just plain wrong.)

**Comment by skylarmb** [comment]
You are correct that these 3 fields are nullable. Here is a PR: https://github.com/plaid/plaid-node/pull/313
