### ISSUE TITLE
open source proects

### ISSUE THREAD

**Issue by c316** [plaid/plaid-node#31]
Do you know of any open source projects using plaid-node? It would be great to look at the patterns they're using.

**Comment by idris** [comment]
https://github.com/asm-products/coinvest-io

**Comment by c316** [comment]
@idris Thanks

**Comment by freeredpill** [comment]
@idris Thanks for answering @c316's question. (I had the same question!)

@c316, what did you learn from the patterns in Coinvest.io?

**Comment by michaelckelly** [comment]
@freeredpill @idris @c316 

The [examples](https://github.com/plaid/plaid-node#examples) section of the README has been significantly expanded and covers a wider range of use cases.

I'm going to go ahead and close this - if you'd like to see a particular example or best practices for a particular Plaid API flow, please open a new issue!
