### ISSUE TITLE
Missing "merchant_name" in Transaction interface

### ISSUE THREAD

**Issue by muinmomin** [plaid/plaid-node#322]
[June change log](https://blog.plaid.com/changelog-june-2020/) added a `merchant_name` field to transactions, but it's missing in the interface in this node package

**Comment by dhwaneetbhatt** [comment]
I can take this up, please assign it to me.

**Comment by cgfarmer4** [comment]
@muinmomin thanks for the report. We'll be shipping the new version on 7/20/20.
