### ISSUE TITLE
Wrong type definition for AssetReportGetPdfResponse

### ISSUE THREAD

**Issue by javierglatstein** [plaid/plaid-node#328]
Hi, I've updated form plaid-node v4.3.0 to v5.2.0 and the client behaves differently here although the type definitions are the same. Ive also downgraded to v4.11.0 and the issue was fixed, so I think the problem was included in v5.x.x.

When using the client's 'getAssetReportPdf' API the types definition says its response 'AssetReportGetPdfResponse', contains a buffer attribute of type Buffer ([here](https://github.com/plaid/plaid-node/blob/master/index.d.ts#L658)).

I've checked the API implementation and it seems that it is being called properly asking for binary data. Based on [PlaidClient.js](https://github.com/plaid/plaid-node/blob/master/lib/PlaidClient.js#L376) and [plaidRequest.js](https://github.com/plaid/plaid-node/blob/master/lib/plaidRequest.js#L56).

However when using the client, the buffer's typeof is string instead of object. It can also be checked by the debugger, so I assume it might be something between the client and Plaid internal APIs.

At this point I am not sure if there is a bug in the type definition stating that buffer is of Buffer type instead of string or if it is on Plaid's APIs.

This is my first time reporting a bug here on Github so if you need any more information, screenshots or anything to reproduce this please let me know.

**Comment by cgfarmer4** [comment]
hi @javierglatstein- Thanks for the report. Looking into this.

**Comment by davidzhanghp** [comment]
@javierglatstein thanks for your input here. This is possibly a change because we moved from using request to axios. Let me dig in further

**Comment by davidzhanghp** [comment]
I have tested and it appears that the returned object is a buffer

**Comment by theoephraim** [comment]
while the type is fixed, it looks like your docs are not - https://plaid.com/docs/api/products/#asset_reportpdfget
