### ISSUE TITLE
Support Auth & Upgrade endpoint

### ISSUE THREAD

**Issue by sidazhang** [plaid/plaid-node#33]
There are a couple of endpoints that are currently unsupported:

https://www.plaid.com/docs/#auth
https://www.plaid.com/docs/#upgrade

Would you be able to add support for them?

**Comment by j4ustin** [comment]
@sidazhang 

Yes! 

There will be a huge rewrite of this library coming up in the next couple of weeks. It will have all of the features of this library: https://github.com/plaid/plaid-ruby. 

If you have any suggestions please let me know and I'll take them into consideration when writing the new package.

**Comment by sidazhang** [comment]
Do you have a timeline? 

I am currently integrating Plaid and I am trying to figure out if I should write a node client myself or wait for you guys

**Comment by j4ustin** [comment]
@sidazhang I was hoping to have it out before the 15'th of April, but if you are on a shorter timeline I can try to bump up the release date to something that would closely match your schedule.

**Comment by sidazhang** [comment]
@j4ustin Thank you very much for the prompt response. 15th of April is an awkward date. It is 2 weeks away so I can't justify writing a client for plaid, but because it is 2 weeks away I don't want to stop development for 2 weeks either.

Would you be able to bump the release date? I would really greatly appreciate it!

**Comment by j4ustin** [comment]
@sidazhang No problem! Let me get back to you with a release date thats a bit closer to this half of the month.

**Comment by sidazhang** [comment]
Hi @j4ustin, Do you have any news of the planned release date? Thank you!

**Comment by j4ustin** [comment]
@sidazhang I was planning on getting the build mostly complete this weekend, and putting out a release data ASAP. Once I get into the details I'll update with a release date.

**Comment by j4ustin** [comment]
@sidazhang Worked on it a bit this weekend. I'm aiming for an end of week release. Sorry it couldn't be sooner, I'm building this afternoons mostly.

**Comment by sidazhang** [comment]
Hey @j4ustin, how is the build coming along? Wanted to ping you and see if maybe there is a version I could test for you

**Comment by scottyli** [comment]
@j4ustin any progress? Deciding whether to wait for this or build a client myself.

**Comment by sidazhang** [comment]
@j4ustin Any news? Would you be able to give some indications on when this would be available? 

I am trying to gauge whether we should write our own client. We would have had written our own client 3 weeks ago if we knew this would not be available until now.

It is not problems at all if you can't release it for another few weeks. But it would be greatly appreciated if you could give us a realistic timeline so that we know how to prioritize development.  Because we have been stuck in limbo the past weeks as we were waiting on this.

**Comment by j4ustin** [comment]
@sidazhang @scottyli Sorry for the long delay here guys. I'm discussing next moves with the Plaid team for this release, but outside factors have gotten in the way of me getting this completed.

**Comment by sidazhang** [comment]
@j4ustin Would you be able to release an Alpha build to us in private so that we can continue development. (I will not expect backward compatibility in future release, because if you don't release an alpha build, I need to write my own client anyway)

**Comment by whockey** [comment]
hi @sidazhang - this was resolved in https://github.com/plaid/plaid-node/pull/34.
