### ISSUE TITLE
All of your API methods are under 'POST' methods

### ISSUE THREAD

**Issue by toniree** [plaid/plaid-node#333]
On the page with the header "Plaid Quickstart Success! You just created an Item by linking your account." of the Node quickstart app

**Comment by anjiren** [comment]
Hi @toniree! Those API methods are correctly labeled, yes those are all POST requests. Is this issue about including examples of non-POST requests? Just trying to understand what you are looking for here.

**Comment by toniree** [comment]
I was thinking maybe whoever listed out the methods forgot to change them to be the correct type of requests, but having become more familiar with Plaid it seems you guys need to use POST requests even for simple Getters due to the token exchange mechanism?

**Comment by skylarmb** [comment]
@toniree correct, we use POST requests for all requests 🏣  (post_office emoji)

Closing as this is not an issue :)
