### ISSUE TITLE
getInstitutionById with options not returning InstitutionWithInstitutionData

### ISSUE THREAD

**Issue by willshelley** [plaid/plaid-node#335]
Using typescript in node struggling to get typed definition of InstitutionWithInstitutionData just receiving Instituition from promise.

plaid@5.2.0
typescript@3.9.6

**Comment by willshelley** [comment]
Solved by casting the institution as InstitutionWithInstitutionData

**Comment by ankitjena** [comment]
@willshelley can you help me with the casting. Thanks
