### ISSUE TITLE
Typescript AccountCommon and Account has null for non-null types

### ISSUE THREAD

**Issue by mozeryansky** [plaid/plaid-node#338]
The AccountCommon and Account type marks some fields as "string | null" when the online documentation doesn't say these values are optional.

Account: https://plaid.com/docs/#accounts
Balance: https://plaid.com/docs/#balance-object

```
  interface AccountCommon {
    account_id: string;
    mask: string | null;
    name: string | null;  <=== not nullable
    official_name: string | null;
    subtype: string | null;   <=== not nullable
    type: string | null;  <=== not nullable
    verification_status:  <=== not nullable
      | 'pending_automatic_verification'
      | 'pending_manual_verification'
      | 'manually_verified'
      | 'automatically_verified'
      | null;
  }

  interface Account extends AccountCommon {
    balances: {
      available: number | null;
      current: number | null;  <=== not nullable
      limit: number | null;
      iso_currency_code: string | null;
      unofficial_currency_code: string | null;
    };
  }
```

Can either the typescript types be fixed or the documentation mention that it can null?

**Comment by skylarmb** [comment]
hi there @mozeryansky thanks for filing this! We will apply a fix for this the next time we have breaking changes to release, since this is not a backwards-compatible change for those who use typescript

**Comment by skylarmb** [comment]
actually looks like we have some breaking changes lined up... ill see if i can get this in

**Comment by skylarmb** [comment]
#342 was merged.  just thought i would flag that `verification_status` is actually nullable. it will be null if you are not using Auth or if the item was verified via the Instant Auth or Instant Match methods

**Comment by mozeryansky** [comment]
@skylarmb Thanks! I see that other parts of the doc mention it could be null but the field in the online doc doesn't say "nullable" like the other ones: plaid.com/docs/#account-schema

**Comment by skylarmb** [comment]
@mozeryansky good catch. looks like error is already fixed in our new beta docs: https://plaid.com/docs-beta/api/accounts/#retrieve-accounts
