### ISSUE TITLE
Latest release and latest tag does not match

### ISSUE THREAD

**Issue by mozeryansky** [plaid/plaid-node#339]
The current latest tag is 5.2.0 but npm says the latest version is 6.0.0.

I see the package.json file was updated and most likely a release was pushed to npm, but it was confusing to see the latest release tag was not 6.0.0. I noticed since it was a breaking change and I saw the Client call changed, but I'm not sure what else changed.

Also GitHub shows the latest is 2.7.0:
<img width="187" alt="Screen Shot 2020-07-27 at 12 36 48 AM" src="https://user-images.githubusercontent.com/3287719/88503990-430f9380-cfa1-11ea-8ac9-a63af2694d03.png">

**Comment by davidzhanghp** [comment]
hi @mozeryansky  thank you so much for bringing this to our attention. we will fix it right away

**Comment by davidzhanghp** [comment]
the tag has been updated.

I am a bit confused, as I see under https://github.com/plaid/plaid-node/releases

![image](https://user-images.githubusercontent.com/38868412/88570511-2eb3b100-d00a-11ea-8efe-78504b775197.png)

**Comment by davidzhanghp** [comment]
I found what you are talking about. That is quite strange. 

I will follow up with github on this one.

Closing this issue for now, thanks again for raising.

**Comment by davidzhanghp** [comment]
I published a new release on github, which updated the widget. Thanks again!

![image](https://user-images.githubusercontent.com/38868412/88571661-02992f80-d00c-11ea-91db-d15dd4dc5a69.png)

**Comment by mozeryansky** [comment]
Odd that it said 7 days ago for you, says 6 minutes for me. All good now, thanks!

<img width="870" alt="Screen Shot 2020-07-27 at 1 21 02 PM" src="https://user-images.githubusercontent.com/3287719/88571678-075de380-d00c-11ea-8f3d-57c4ecc2c014.png">
