### ISSUE TITLE
Error when creating a new plaid Client object

### ISSUE THREAD

**Issue by thecoolwinter** [plaid/plaid-node#345]
I'm running plaid in a node.js 10 environment, in a GCP cloud function. When using the sandbox, my initialization went fine. But, now that I've moved into development mode, the initialization throws this error:
```
functions: Error: Missing Plaid "secret"
    at new Client (/Users/.../functions/functions/node_modules/plaid/lib/PlaidClient.js:20:11)
    at initPlaid (/Users/.../functions/functions/index.js:36:23)
    at /Users/.../functions/functions/index.js:168:5
    at /usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:583:20
    at /usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:558:19
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:4:12)
    at runFunction (/usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:555:12)
    at /usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:582:15
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:4:12)
    at runHTTPS (/usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:578:12)
```
Here's the code I'm using to make the Client object. I've made sure each variable is giving a valid string with the correct secrets and everything.
```javascript
plaidClient = new plaid.Client({
            clientID: plaidClientId,
            secret: plaidSecret,
            env: plaid.environments.development,
            options: {
              version: '2019-05-29', 
            }
          })
```

**Comment by thecoolwinter** [comment]
I've figured it out. In the /lib/PlaidClient.js the function params don't match what's in the example and getting started pages. Instead of passing an object, it takes four strings and an options object.

```javascript
function Client(client_id, secret, public_key, env, options) {
    ...
```

I was getting this error because plaid was finding the secret param nil.

If someone could update the README it'd be useful for future people.

**Comment by gorbat-o** [comment]
What is supposed to be the `public_key` when we are not supposed to use it anymore?
It says `link_token`. Which I also don't understand why it is here, because we are supposed to use it to get the `publicTokenExchange`. 
I am trying to create the link token with `plaidClient.createLinkToken`
![image](https://user-images.githubusercontent.com/59470354/99202468-1c4db680-2764-11eb-8527-0b78f4daa7a1.png)

**Comment by gorbat-o** [comment]
Alright, the solution is to actually use what the documentation says.
as of this:
```
const plaidClient = new plaid.Client({
    clientID: functions.config().plaid.clientid,
    secret: functions.config().plaid.secret,
    env: plaid.environments.development,
});
```
And to be sure you are using at least the version 7.0.0. 
For some reason when adding a package with npm, it is installing the 2.1.0 which is absolutely not right.

**Comment by killerrings** [comment]
It's still fetching me some error and I'm not being able to find a way around it. 
![image](https://user-images.githubusercontent.com/48016557/142599222-9dd389eb-eb49-41a6-93eb-e6cfec9b01f7.png)

**Comment by sarthak-arora1997** [comment]
i am getting the exact same error, any form of help would be really appreciated, very close to my deadline for this one, please help !!
