### ISSUE TITLE
getInstitutionById with options not returning InstitutionWithInstitutionData 

### ISSUE THREAD

**Issue by aditsachde** [plaid/plaid-node#346]
This was mentioned in #335 without a proper fix. `getInstitutionById` is defined as the following.

```js
    getInstitutionById(
      institutionId: string,
      options?: GetInstitutionByIdOptions,
    ): Promise<GetInstitutionByIdResponse<Institution>>;
    getInstitutionById(
      institutionId: string,
      options: {include_optional_metadata: true},
    ): Promise<GetInstitutionByIdResponse<InstitutionWithInstitutionData>>;
```

Because the first definition marks the options parameter as optional, typescript seems to always match the function to that definition, even if options is explicitly defined like in the second definition. Casting, as mentioned in #335 works, but isn't ideal.

**Comment by hanisami** [comment]
Hello
Cast the result you get from plaid to `Plaid.GetInstitutionByIdResponse<Plaid.InstitutionWithDisplayData>`

**Comment by jzrandall** [comment]
I believe if the more specific definitions are moved above the one with the options? parameter, then TS will resolve it properly. I just moved it in my local copy of index.d.ts for Plaid and it fixed the TS error.  If I'm not mistaken, the way they are currently defined means that the more specific definitions will never be applied.

This order should allow TS to match on the more specific options first.

```js
    getInstitutionById(
      institutionId: string,
      options: { include_optional_metadata: true },
    ): Promise<GetInstitutionByIdResponse<InstitutionWithInstitutionData>>;
    getInstitutionById(
      institutionId: string,
      options: { include_status: true },
    ): Promise<GetInstitutionByIdResponse<InstitutionWithStatus>>;
    getInstitutionById(
      institutionId: string,
      options: { include_optional_metadata: true; include_status: true },
    ): Promise<
      GetInstitutionByIdResponse<
        InstitutionWithInstitutionData & InstitutionWithStatus
      >
    >;
    getInstitutionById(
      institutionId: string,
      options?: GetInstitutionByIdOptions,
    ): Promise<GetInstitutionByIdResponse<Institution>>;
```

**Comment by anjiren** [comment]
@jzrandall Thanks for the diagnosis. Opened #362 for the fix.
