### ISSUE TITLE
Clarification on migration from previous versions

### ISSUE THREAD

**Issue by djMax** [plaid/plaid-node#351]
We are trying to migrate from version 2 of this library to version 8 (yikes). I see that the public_key parameter is gone, and that the changelog says it's not required anymore. Does this mean that EXISTING integrations (which use the public key on the mobile app side) will still work? Or do they have to upgrade simultaneously with the back end?

**Comment by cgfarmer4** [comment]
hi @djMax, please file a support ticket [here](https://dashboard.plaid.com) and they'll get you sorted.
