### ISSUE TITLE
Incorrect type definition

### ISSUE THREAD

**Issue by jontas** [plaid/plaid-node#379]
The Plaid [API docs](https://plaid.com/docs/api/products/#investmentsholdingsget) state that the field `security.type` is not nullable, however, the type definitions have it as `type: string | null;`

Same is true for `holding.institution_price`

**Comment by jontas** [comment]
`interface Institution` is missing some properties (eg `routing_numbers`)

**Comment by skylarmb** [comment]
Hi there Jontas. We are moving to a world where we auto-generate this library so we wont have issues with minor type inconsistencies like this. If you would like to preview it, you can check out the beta branch here: https://github.com/plaid/plaid-node/tree/9.0-beta-releases. It's highly unlikely we will fix this before we launch the generated library in a couple weeks from now.

**Comment by jontas** [comment]
Sounds great, thanks for the update!
