### ISSUE TITLE
Issue fetching liabilities data

### ISSUE THREAD

**Issue by cavalos0086** [plaid/plaid-node#388]
# THE PROBLEM
For this scenario I am using sandbox. 
When I include `liabilities` in the product array when creating a new link token, I get the following error `none of your accounts are liability accounts plaid`. I can successfully get the liabilities data without including `liablities` on the product array by calling `getLiabilities()`. 

# ENVIROMENT
Plaid version 8.1.2
Plaid Link React Native 7.0.0rc2

# STEPS TO REPRODUCE
1. Create a link token as per the docs
```
user: {
      client_user_id: userId,
    },
    client_name: '????',
    products: ['auth', 'transactions', 'liabilities'],
    country_codes: ['US'],
    language: 'en'
```
2. connect the item using the generated link token and you will see the error `none of your accounts are liability accounts plaid`

## WORKAROUND
As I mention, I am doing the following:
```
user: {
      client_user_id: userId,
    },
    client_name: '????',
    products: ['auth', 'transactions'], // <------ NO LIABILITIES HERE
    country_codes: ['US'],
    language: 'en'
```
2. Connect the item successfully using the link token from step 1. 
3. Use the link token to get liabilities data `plaidClient.getLiabilities(accessToken);`
4. Liabilities data is returned. 

## EXPECTED RESULTS
I should be able to get all the liabilities data when I am connecting the item using the generated link token, not in a second call.

**Comment by skylarmb** [comment]
Hi there @cavalos0086! Thanks for submitting this, this definitely looks like it could be an issue with our sandbox environment. Could you file a support ticket through the [developer dashboard](https://dashboard.plaid.com/support/new/product-and-development/product-troubleshooting/response-codes)? This github repo is for plaid-node, our node wrapper for the Plaid API, and this is not an issue with plaid-node, this an an error coming from the Plaid API. Thanks!
