### ISSUE TITLE
Best practice for associating a webhook trigger with a user

### ISSUE THREAD

**Issue by shalbert94** [plaid/plaid-node#395]
When a webhook is sent, I'd like to know which user the hook is associated with. What is the best practice for associating a user with a webhook?

Apologies if this is a dumb question, I've never implemented consumption of a webhook before.

**Comment by daniellacoste** [comment]
Hey @shalbert94 , Daniel from Plaid Support here. No worries, there is no such thing as a dumb question:

> I'd like to know which user the hook is associated with. What is the best practice for associating a user with a webhook?

The response body of each Plaid webhook will contain an `item_id` ([example](https://plaid.com/docs/api/webhooks/#ItemErrorWebhook-item-id)) field which you use to reference back to your application's user. If you do not have the `item_id` stored in your app (but you are properly persisting your `access_token`s), then you can issue an [`/item/get` API request](https://plaid.com/docs/api/items/#itemget) to map the webhook's `item_id` to your stored `access_token`.

Please note that it is up to you for how your application relates an `item_id` back to a specific user — this usage can vary based on your use-case.

I hope this helps — please reply back if you have any additional questions ([or please open a Support case from your Plaid Dashboard](https://dashboard.plaid.com/support)). Cheers!
