### ISSUE TITLE
Async await support for requests with schedule object: createPayment

### ISSUE THREAD

**Issue by willshelley** [plaid/plaid-node#401]
Will there be support for types within the schedule object of createPayment for async await?

<img width="304" alt="Screenshot 2021-02-02 at 11 40 57" src="https://user-images.githubusercontent.com/39528236/106596020-5bfa9200-654c-11eb-98f0-408fb18b0e72.png">

<img width="1033" alt="Screenshot 2021-02-02 at 11 51 30" src="https://user-images.githubusercontent.com/39528236/106596503-05418800-654d-11eb-82c4-4ff2bf16951b.png">

Cheers Will

**Comment by cgfarmer4** [comment]
hi @willshelley- the latest type updates can be found in our beta release slated for GA in a few months. Please reopen if that doesn't help.
