### ISSUE TITLE
Work with fetch/non-Node environments

### ISSUE THREAD

**Issue by jonahbron** [plaid/plaid-node#425]
Different runtime environments (such as Deno or Cloudflare Workers) don't support the Node APIs used by Axios (the library that plaid-node uses for making requests).  Plaid's client library should be made compatible with these emerging runtimes.

**Comment by cgfarmer4** [comment]
@jonahbron we have no plans to move away from `axios`. You can generate different types of node APIs using our OpenAPI file. https://github.com/plaid/plaid-openapi

**Comment by jonahbron** [comment]
To be clear, your intent is to not support any JS runtimes besides Node?

**Comment by cgfarmer4** [comment]
We support over 40+ languages with OpenApi. This repo will not provide deno tests as it’s a very early language. The typescript generator supports deno. We have examples of generation on the plaid-openapi repo. 

https://openapi-generator.tech/docs/generators/typescript/
