### ISSUE TITLE
Plaid Node 9 Beta - Lost Support For /income/verification/paystubs/get

### ISSUE THREAD

**Issue by HoyaBoya** [plaid/plaid-node#443]
# About

There's an endpoint to `GET /income/verification/paystubs/get` that is mentioned in the Beta 10 documents that we were using in the version 8 of Plaid Node. I am not sure if if this API call is no longer going to be supported or if the method got lost in the 9 Beta, but it would be great to get it back again.

Searching the code, only shows the call to get the single paystub.

```
4078: * IncomeVerificationPaystubGetRequest defines the request schema for `/income/verification/paystub/get`.
4080: * @interface IncomeVerificationPaystubGetRequest
4082:export interface IncomeVerificationPaystubGetRequest {
4086:     * @memberof IncomeVerificationPaystubGetRequest
4092:     * @memberof IncomeVerificationPaystubGetRequest
4098:     * @memberof IncomeVerificationPaystubGetRequest
4103: * IncomeVerificationPaystubGetResponse defines the response schema for `/income/verification/paystub/get`.
```

## Related PR

https://github.com/plaid/plaid-node/pull/432

/cc @tylernappy

**Comment by HoyaBoya** [comment]
FWIW, I simply just added `incomeVerificationPaystubsGet` to the `api.js` in our fork and pointed `package.json` to that. Everything is 👍  for us temporarily. The documentation pointed to a broken link for the Open API spec so there's no way for me to help out / contribute, since from what I understand, the entire library is auto-generated.

https://github.com/plaid/plaid-node/blob/9.0.0-beta-release/CONTRIBUTING.md

Look forward to getting this resolved!

**Comment by phoenixy1** [comment]
@HoyaBoya this has now been added in the latest version of the openapi spec and should be fixed the next time we generate the libraries.

**Comment by HoyaBoya** [comment]
Confirmed that this works with the latest Plaid 9 beta! Thanks for the fix.
