### ISSUE TITLE
Plaid 9 Beta - Inconsistent Interface To postIncomeVerificationCreate

### ISSUE THREAD

**Issue by HoyaBoya** [plaid/plaid-node#444]
# About

We're trying to move to Plaid 9 Beta and there's some erratic behavior on the Plaid Income Verification calls to start the income verification request. We've configured the library to take `baseOptions`  -> `headers` with our credentials but the `postIncomeVerificationCreate` call, which I believe is analogous to the original income verification create does not work unless I explicitly pass the credentials again.

Would be nice to make this consistent, but not blocking.

```
{
  "display_message": null,
  "documentation_url": "https://plaid.com/docs/?ref=error#invalid-request-errors",
  "error_code": "MISSING_FIELDS",
  "error_message": "the following required fields are missing: client_id, secret",
  "error_type": "INVALID_REQUEST",
  "request_id": "1gpbtjzzyVi3qRc",
  "suggested_action": null
}
```

## Plaid 8
```
const response = await plaid.createIncomeVerification(webhook)
```

## Plaid 9 Beta
```
    const { data } = await plaid.postIncomeVerificationCreate({
      client_id: process.env.PLAID_CLIENT_ID,
      secret: process.env.PLAID_SECRET,
      webhook
    })
```

/cc @tylernappy

**Comment by HoyaBoya** [comment]
This also applies to the other income verification endpoints.

**Comment by phoenixy1** [comment]
Thank you for reporting! This is an expected issue -- the Income Verification team is currently working on making these updates in order to support the new client libraries.

**Comment by HoyaBoya** [comment]
Confirmed that this is fixed! Thanks.
