### ISSUE TITLE
Plaid 9 Beta - Income Verification Download Documents Returns A Corrupted Zip

### ISSUE THREAD

**Issue by HoyaBoya** [plaid/plaid-node#448]
# About

The `.incomeVerificationDocumentsDownload` is returning a corrupted zip file which can neither be opened up by Mac OS nor processed by a library such as [AdmZip](https://www.npmjs.com/package/adm-zip). I know the endpoint works since when I revert my code and used Plaid 8 with the PR below (biased since I wrote it), I can open the zip for the same `income_verification_id` that fails in Plaid 9.

If I had to guess, it is due to the `binary` not being preserved which was the [trick](https://github.com/plaid/plaid-node/issues/448) in the PR below for Plaid 8.

## Related PRs

https://github.com/plaid/plaid-node/pull/434

/cc @tylernappy

**Comment by phoenixy1** [comment]
cc: @stephenjayakar @cgfarmer4

**Comment by HoyaBoya** [comment]
Confirmed that this is fixed when you pass `responseType: 'arraybuffer'` to the method. Thanks everyone.

/cc @rajeevmehrotra
