### ISSUE TITLE
JWT for integration testing the webhook receiver

### ISSUE THREAD

**Issue by shalomhalbert** [plaid/plaid-node#454]
To run an integration test on a URL that receives Plaid's webhook it's necessary to have a valid JWT. This is normally provided by Plaid's webhook under the `plaid-verification` header. I know you can indirectly generate the JWT by using Plaid's [/sandbox/item/fire_webhook](https://plaid.com/docs/api/sandbox/#sandboxitemfire_webhook) endpoint and then taking the JWT from the ensuing request to my webhook receiver. However, that system will make the tests slow and messy. 

Is there a better way to generate the JWT value?

**Comment by phoenixy1** [comment]
currently, there is not. We know webhook verification is a fairly ugly part of the UX and will take this feedback as we think about how we might improve it for the future.
