### ISSUE TITLE
Plaid 3.5.1 and Stripe 17.1.2 seem to conflict, is this the suggested approach (excluding from either seems to work - Plaid 3.4.1 didn't seem to have the issue)?

### ISSUE THREAD

**Issue by skillenj79** [plaid/plaid-node#472]
Plaid 3.5.1 and Stripe 17.1.2 seem to conflict, is this the suggested approach (excluding from either seems to work - Plaid 3.4.1 didn't seem to have the issue)?

    implementation('com.plaid.link:sdk-core:3.5.1') {
        exclude group: 'org.bouncycastle'
    }
    implementation 'com.stripe:stripe-android:17.1.2'

_Originally posted by @jt-gilkeson in https://github.com/plaid/plaid-link-android/issues/187#issuecomment-913902925_

**Comment by phoenixy1** [comment]
Closing this task as it doesn't seem to be relevant to this repo -- if you meant to ask about the original issue, please comment on that thread. Thanks!
