### ISSUE TITLE
plaid.Client is not a Constructor

### ISSUE THREAD

**Issue by killerrings** [plaid/plaid-node#487]
I'm receiving this error repeatedly and cannot find a way around it
![image](https://user-images.githubusercontent.com/48016557/142599611-8d3b5de8-830d-416f-a7ff-51a2679ebbde.png)

**Comment by phoenixy1** [comment]
The way you're trying to call that looks pretty different from the example in the readme -- have you tried doing it like this?

```
import { Configuration, PlaidApi, PlaidEnvironments } from 'plaid';

const configuration = new Configuration({
  basePath: PlaidEnvironments.sandbox,
  baseOptions: {
    headers: {
      'PLAID-CLIENT-ID': CLIENT_ID,
      'PLAID-SECRET': SECRET,
    },
  },
});

const client = new PlaidApi(configuration);
```

**Comment by killerrings** [comment]
@phoenixy1 I have not tried it out yet. But the Plaid documentation also mentions the way I did it.
![image](https://user-images.githubusercontent.com/48016557/142713627-2db7864f-04ea-4bd5-b732-776ea1f85521.png)
![image](https://user-images.githubusercontent.com/48016557/142713631-c99c2b25-3736-44b3-a2eb-9ee04554431b.png)

**Comment by phoenixy1** [comment]
@killerrings got it -- the "legacy libraries" section is meant for developers on legacy versions of the client libraries. If you are using the latest version of the libraries, you should use the "current libraries" example.
