### ISSUE TITLE
Create linkToken with account_selection_enable failed

### ISSUE THREAD

**Issue by panda622** [plaid/plaid-node#489]
`{"stack":["GET relink"],"config":{"url":"https://sandbox.plaid.com/link/token/create","method":"post","data":"{\"user\":{\"client_user_id\":\"7ae48680-c122-47c1-95fd-5ea331fa3173\"},\"client_name\":\"Test Name\",\"country_codes\":[\"US\"],\"language\":\"en\",\"webhook\":\"https://test-domain.com/api/v1/plaid/webhook\",\"redirect_uri\":\"https://test-domain/plaid-oauth\",\"access_token\":\"access-sandbox-c4ffdfca-f20f-401b-a75b-9a86ceb8a20c\",\"link_customization_name\":\"account_selection_v2_customization\",\"update\":{\"account_selection_enabled\":true}}","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"Plaid Node v9.7.0","Plaid-Version":"2020-09-14","PLAID-CLIENT-ID":"PlAID_ID","PLAID-SECRET":"PLAID_SECRET","Content-Length":434},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false}}}`

I got this error when trying to creat linked-token with account selection enable. Anyone can help me?

**Comment by phoenixy1** [comment]
@panda622 it's a bit difficult to see what the actual error is here -- can you perhaps provide the error details from the activity log in the plaid dashboard? (after logging into the dashboard, go to activity->logs).

**Comment by phoenixy1** [comment]
Closing due to insufficient information to troubleshoot -- please reopen with more information if you need, thanks
