### ISSUE TITLE
Not possible to verify a Stripe connected account

### ISSUE THREAD

**Issue by jasonlewicki** [plaid/plaid-node#495]
I'm not seeing an option in the API docs, so I'm not sure where to put this.

My use case is to verify ownership of a bank account using Plaid's auth. The bank account is tied to a connected account on stripe. The token returning from 

```
const {stripe_bank_account_token} = await plaidClient.createStripeToken(accessToken, plaidAccountId)
```

is only applicable to the master stripe account. That makes sense, since the API call does not accept a `stripe_account_id` parameter.

**Comment by phoenixy1** [comment]
Hi Jason, would it be possible for you to file a support ticket via the Dashboard for this one? I don't think it's a problem specifically with the Node library, and Developer Support would be better positioned than us to understand the correct product behavior here (honestly I am not sure of the correct answer myself). Thanks!

**Comment by phoenixy1** [comment]
Closing this issue as it's not specifically related to Node libraries and would be best handled by Support.
