### ISSUE TITLE
Cannot mock implementation to test

### ISSUE THREAD

**Issue by spacesean** [plaid/plaid-node#511]
Hi! I'm trying to create unit tests. We use Jest with Supertest and previously created mock implementations for our other APIs like Stripe. I've been trying to mock the Plaid API in a similar fashion, but I am having trouble with my test-server not initializing the PlaidApi correctly.

Note: I'm *not* trying to call `plaid.createLinkToken()` in a test, or anything similar. I am unit testing my server by sending Supertest requests. We have the stripe mock working where any call to `stripe.` will return some mock response like { id: "cus_323" }

For Stripe, it seems pretty straight forward because you can use:
```javascript
jest.mock("stripe", () => { // mocked responses })
```

Stripe is imported and initialized via:
```javascript
import Stripe from "stripe";
const stripe = new Stripe(key, options);
```

But the Plaid API is implemented differently:
```javascript
import {
    Configuration,
    PlaidApi,
} from "plaid";

const configuration = new Configuration(options);
const plaid = new PlaidApi(configuration);
```

I can't use `jest.mock("PlaidApi", ...)` because that returns an error.

So I am wondering what the best way is to mock the Plaid module so Supertest can use my real server but I can mock the Plaid calls. Why can't Plaid be imported like `import Plaid from "plaid"`? Any guidance you can provide would be appreciated.

**Comment by andreiseceavsp** [comment]
What error do you get? Did you tried?
```
jest.mock("plaid", () => {
  return {
    Configuration: jest.fn(),
    PlaidApi: jest.fn(() => {
      return {
        getAuth: jest.fn()
      }
    }),
  }
})
```

**Comment by spacesean** [comment]
I was able to mock the plaid constructor ok but can't get any specific methods on the mock to work.

```javascript
jest.mock("plaid", () => ({
    // Configuration
    Configuration: jest.fn(),
    CountryCode: {
        Us: "US",
    },
    PlaidApi: jest.fn(),
    Products: {
        Assets: "assets",
        Auth: "auth",
        Balance: "balance",
    },
    PlaidEnvironments: {
        sandbox: "sandbox",
        development: "development",
        production: "production",
    },
    // Methods
    linkTokenCreate: jest.fn(() => ({
        data: {
            link_token: "link-sandbox-threelittlepigs",
            expiration: "2024-03-27T12:56:34Z",
            request_id: "sseBBcl2FsoQuR5kMnn"
        }
    })),
}))
```

I am getting `TypeError: plaid.linkTokenCreate is not a function` when my server tries to call `plaid.createLinkToken(input)`

**Comment by spacesean** [comment]
Oh, I see what I was doing now. To use plaid we create an instance of the PlaidApi by calling `PlaidApi(configuration)` and then that returned object is where the methods like `linkTokenCreate` reside. The API methods should have been placed inside of `PlaidApi` mock function instead of at the same level:

```javascript
PlaidApi: jest.fn(() => ({
    // Methods
    linkTokenCreate: jest.fn(() => ({
        data: {
            link_token: "link-sandbox-threelittlepigs",
            expiration: "2024-03-27T12:56:34Z",
            request_id: "sseBBcl2FsoQuR5kMnn"
        }
    })),
})),
```

**Comment by JaffParker** [comment]
Hello, sad to reopen this, but I'm facing the same issue. Here's how I'm mocking 'plaid':

```ts
import { Configuration, PlaidApi } from 'plaid'

jest.mock('plaid', () => ({
  Configuration: jest.fn(),
  PlaidApi: jest.fn(() => ({
    linkTokenCreate: jest.fn(),
    itemPublicTokenExchange: jest.fn(),
    transactionsSync: jest.fn(),
  })),
  PlaidEnvironments: {
    sandbox: 'https://sandbox.plaid.com',
  },
}))
```

Then initialize it like this:

```ts
beforeAll(() => {
  plaidApiMock = new PlaidApi({} as Configuration) as jest.Mocked<PlaidApi>
  plaid = new Plaid(plaidApiMock)
})
```

Where the `Plaid` class is my own. When I run these tests, it uses the actual module and tries to make actual requests. I mock other modules the exact same way and it works fine, so I'm really lost for solutions here... Do I need to do anything special to mock Plaid?

**Comment by phoenixy1** [comment]
Hmm, I'm not aware of anything special you need to do to mock Plaid.

I'm not sure how helpful this will be, but this is what ChatGPT suggested for troubleshooting. Can you try this and let us know if it helped at all?

Ensure Jest is Configured Correctly: Double-check your Jest configuration to ensure that it is set up to use module mocks. If you're using a custom setup file, make sure it's included in your Jest configuration.

Mock Implementation: Ensure that your mock implementation is being used correctly. You can add a console log inside your mock functions to confirm whether they are being called or if the actual implementation is being executed.

Check Import Statements: Make sure the imports in your test files are correctly pointing to the mocked version. If you’re importing the actual module somewhere else, it may cause the real implementation to be used.

Reset Mocks: Use jest.resetAllMocks() in your beforeEach or beforeAll to ensure that your mocks are reset and ready for each test. This can help prevent state leakage between tests.

Check for TypeScript Issues: If you're using TypeScript, ensure that the types align correctly. Sometimes TypeScript can lead to unexpected behavior if the types do not match.

Mocking the Plaid Class: If you have a custom Plaid class that uses the PlaidApi, ensure you’re also mocking its behavior. If the class is instantiating the real PlaidApi, it will use the actual implementation unless it’s mocked.

Mocking at the Top Level: Ensure that your mock is at the top level of your test file. Sometimes the order of imports and mocks can affect whether the mock is applied correctly.

Here’s an example adjustment to your mocking approach:

```
import { Configuration, PlaidApi } from 'plaid'

// Mock PlaidApi and Configuration
jest.mock('plaid', () => {
  const mockLinkTokenCreate = jest.fn();
  const mockItemPublicTokenExchange = jest.fn();
  const mockTransactionsSync = jest.fn();

  return {
    Configuration: jest.fn(),
    PlaidApi: jest.fn(() => ({
      linkTokenCreate: mockLinkTokenCreate,
      itemPublicTokenExchange: mockItemPublicTokenExchange,
      transactionsSync: mockTransactionsSync,
    })),
    PlaidEnvironments: {
      sandbox: 'https://sandbox.plaid.com',
    },
  };
});

let plaidApiMock;

beforeAll(() => {
  plaidApiMock = new PlaidApi({} as Configuration);
});

// In your tests, you can use plaidApiMock.linkTokenCreate, etc.
```

With these adjustments, check if your tests still call the actual API. If they do, please provide additional context, such as how you're importing and using the Plaid class in your tests. This will help narrow down the issue further.

**Comment by JaffParker** [comment]
That's funny because I used Copilot to generate my tests :D It's taking us over.

I've already gone through some of those points, everything looks right. Maybe it's time for StackOverflow, actually.
