### ISSUE TITLE
Type '"auth"' is not assignable to type 'Products'.

### ISSUE THREAD

**Issue by Paulsonbigi** [plaid/plaid-node#512]
I was trying to generate a link  token but it keeps breaking my app, please what am i doing wrong.

`plaidLinkTokenService =  async ( userId: string): Promise<
        [success?: boolean, data?: Record<string, any>, status?: number]> => {
        try {
            const tokenResponse = await plaidClient.linkTokenCreate({
                user: {
                  client_user_id: userId,
                },
                client_name: 'Sila Test App',
                products: ["auth"],
                country_codes: ["US"],
                language: 'en',
                webhook: 'https://webhook.sample.com',
                redirect_uri: 'https://domainname.com/oauth-page.html',
              });
        } catch (error) {
            console.log("eejenfejnf", error)
            const response = await error.response;
            return [false, response.data, response.status];
        }
    };`

**Comment by phoenixy1** [comment]
There's isn't enough information here to debug and I think you asked this on another thread and got an answer, so closing this out for now. Please feel free to respond if you're still having trouble and I will re-open the issue.
