### ISSUE TITLE
Cannot find name 'Products'.

### ISSUE THREAD

**Issue by Paulsonbigi** [plaid/plaid-node#513]
Where is the Product object coming from please when trying to linkTokenCreate mwthods, Can anyone help out

**Comment by andreiseceavsp** [comment]
@Paulsonbigi See [documentation](https://plaid.com/docs/api/tokens/#link-token-create-request-products). Specifically for linkTokenCreate you need `products = ['auth']`

**Comment by phoenixy1** [comment]
Alternatively, `const { Products } = require("plaid");`
