### ISSUE TITLE
Add "solid" to ProcessorTokenCreateRequestProcessorEnum

### ISSUE THREAD

**Issue by igorbraz89** [plaid/plaid-node#514]
Context: The Plaid documentation to add Solid to my APP recommends to create the processor token using the value "solid" for the header `processor`.(https://plaid.com/docs/auth/partnerships/solid/)

```
# Create a processor token for a specific account id.
curl -X POST https://sandbox.plaid.com/processor/token/create \
  -H 'Content-Type: application/json' \
  -d '{
    "client_id": "PLAID_CLIENT_ID",
    "secret": "PLAID_SECRET",
    "access_token": "ACCESS_TOKEN",
    "account_id": "ACCOUNT_ID",
    "processor": "solid"
  }'
```
Problem: The ENUM ProcessorTokenCreateRequestProcessorEnum is outdated and does not contains this value:
```
/**
    * @export
    * @enum {string}
    */
export enum ProcessorTokenCreateRequestProcessorEnum {
    Dwolla = 'dwolla',
    Galileo = 'galileo',
    ModernTreasury = 'modern_treasury',
    Ocrolus = 'ocrolus',
    PrimeTrust = 'prime_trust',
    Vesta = 'vesta',
    Drivewealth = 'drivewealth',
    Vopay = 'vopay',
    Achq = 'achq',
    Check = 'check',
    Checkbook = 'checkbook',
    Circle = 'circle',
    SilaMoney = 'sila_money',
    Rize = 'rize',
    SvbApi = 'svb_api',
    Unit = 'unit',
    Wyre = 'wyre',
    Lithic = 'lithic',
    Alpaca = 'alpaca',
    Astra = 'astra',
    Moov = 'moov',
    TreasuryPrime = 'treasury_prime'
}
```
Proposal: Add `Solid='solid'` to this enum.

Now about my situation:

I am implementing this integration and I have to apply a workaround to make it work `"solid" as ProcessorTokenCreateRequestProcessorEnum`. So, nothing blocking but for sure something good to update =D

**Comment by igorbraz89** [comment]
cc @[phoenixy1](https://github.com/phoenixy1)

**Comment by phoenixy1** [comment]
thanks! This will be fixed in our next client library release.

**Comment by igorbraz89** [comment]
@phoenixy1 I appreciate it sir, thank you so much =D

**Comment by phoenixy1** [comment]
this should now be fixed, so closing this issue
