### ISSUE TITLE
Getting Error For createStripeToken

### ISSUE THREAD

**Issue by Saad-Techception** [plaid/plaid-node#515]
Hi, hope that you are doing well, 
                                                     I am trying to integrate STRIPE and ACH but not able to `createStripeToken` Can anyone help or there is new update for the latest version, I am using `2020-09-14` version.  if you see here in [stripe doc ](https://stripe.com/docs/ach) you will see that they are asking to connect it with `createStripeToken` but in older version and documentation i can see that function was there but not now in lates version.

**Comment by phoenixy1** [comment]
The docs on the Stripe site are outdated -- we are working with them to get them fixed. In the meantime, please see https://plaid.com/docs/auth/partnerships/stripe/ instead for the current implementation.
