### ISSUE TITLE
Seeing UPDATE_ACKNOWLEDGED webhook code instead of WEBHOOK_UPDATE_ACKNOWLEDGED

### ISSUE THREAD

**Issue by trex-quo** [plaid/plaid-node#519]
My team has started noticing webhooks come in with the code `UPDATE_ACKNOWLEDGED` instead of `WEBHOOK_UPDATE_ACKNOWLEDGED`. The latter is what is stated as correct in Plaid's documentation and what we have seen coming through historically. Was there an update to the webhook payload that didn't make it into the documentation?

**Comment by phoenixy1** [comment]
I checked and you are definitely right. Looking through the codebase I don't see anything completely obvious on first glance that would have caused this change -- do you know when this change started?

**Comment by trex-quo** [comment]
There was a gap in our logging where we were leaving out the code from the request body so I am not 100% sure. My best guess from the information we have, however, is about 8 days ago.

**Comment by trex-quo** [comment]
After doing some more digging, I can confirm that the last time we received a WEBHOOK_UPDATE_ACKNOWLEDGED webhook was 2022-03-29 14:57:32.857 PDT.

**Comment by phoenixy1** [comment]
@trex-quo thank you for the details! I spoke with the team and a fix for this issue was just deployed. The webhook should be restored to its correct name as of about 30 minutes ago. Thank you for reporting this!

**Comment by trex-quo** [comment]
Thanks for the help!

**Comment by ghernandez-plaid** [comment]
Hi @trex-quo! I hope all is well. My name is Gilberto and I’m on the Developer Relations team at Plaid. I couldn't quite find a good way of getting in contact, so here I am on GitHub! 

Our team is interested in expanding our Plaid community and we’re conducting a bit of research to learn more about how devs engage with us. I was wondering if you'd be interested in participating in a 30 minute research session with me and a member of our research team? You would be compensated with a gift card for your time. 

If you’re interested, let me know and I can send over a Calendly link so we can schedule some time (we could switch to email, too, if you'd prefer). Thanks and hope we get to connect!

**Comment by trex-quo** [comment]
Hi Gilberto, thanks for reaching out! I'd be interested in participating; my email address is trevor@quo.com if you would like to continue discussion over email.

- Trevor

**Comment by ghernandez-plaid** [comment]
Thanks Trevor! I sent you an email. Looking forward to chatting.

- Gilberto

> Hi Gilberto, thanks for reaching out! I'd be interested in participating; my email address is [trevor@quo.com](mailto:trevor@quo.com) if you would like to continue discussion over email.
> 
> * Trevor
