### ISSUE TITLE
creditBankIncomeGet function not picking up clientId and secret from baseOptions in Configuration

### ISSUE THREAD

**Issue by praveshtora** [plaid/plaid-node#527]
Currently with following configuration, all the api's in sdk related to product 'auth' was picking client_id and secret from baseOptions. But while integrating 'income verification' product and using 'creditBankIncomeGet' the client_id and secret needs to be explicitly passed to function.
const configuration = new Configuration({
    basePath: "xxxxx",
    baseOptions: {
        headers: {
            'PLAID-CLIENT-ID': "xxxxx",
            'PLAID-SECRET': "xxxxxxx",
        },
    },

});
const plaidClient = new PlaidApi(configuration);

**Comment by phoenixy1** [comment]
@praveshtora sorry about that! Can you confirm whether this is still happening? I've alerted the team that owns this surface.

**Comment by phoenixy1** [comment]
@praveshtora to elaborate, I checked with the team and they believe this issue may be resolved, so please do let us know whether it's still happening!
