### ISSUE TITLE
client is not authorized to access the following products

### ISSUE THREAD

**Issue by DaLiangLee** [plaid/plaid-node#540]
Hello, I have some accounts_type loan and other not getting transactions when I call the "transactions/get" API, according to the documentation I want to test with "investments/transactions/get", but I get this error
"**error_message": "client is not authorized to access the following products: [\"investments\"]**"

**Comment by ghernandez-plaid** [comment]
> Hello, I have some accounts_type loan and other not getting transactions when I call the "transactions/get" API, according to the documentation I want to test with "investments/transactions/get", but I get this error "**error_message": "client is not authorized to access the following products: ["investments"]**"

Hi @DaLiangLee! It sounds like you're attempting to use Investments in the Development or Production environment. To test Investments in these environments, you'll need to first request access by [submitting a product access request Support ticket](https://dashboard.plaid.com/support/new/product-and-development/product-troubleshooting/request-product-access) explaining your use case. In the meantime, Investments can be tested in [Sandbox](https://plaid.com/docs/sandbox/) without any additional permissions.

**Comment by DaLiangLee** [comment]
> > Hello, I have some accounts_type loan and other not getting transactions when I call the "transactions/get" API, according to the documentation I want to test with "investments/transactions/get", but I get this error "**error_message": "client is not authorized to access the following products: ["investments"]**"
> 
> Hi @DaLiangLee! It sounds like you're attempting to use/test Investments in the Development or Production environment. To test Investments in these environments, you'll need to first request access by [submitting a product access request Support ticket](https://dashboard.plaid.com/support/new/product-and-development/product-troubleshooting/request-product-access) explaining your use case. In the meantime, Investments can be tested in [Sandbox](https://plaid.com/docs/sandbox/) without any additional permissions.

thank you for your reply
Do you mean that this error occurs because the product environment does not have the api permission to apply for investment (I can't log in to the customer's plaid, so I can't view it)

**Comment by DaLiangLee** [comment]
![image](https://user-images.githubusercontent.com/21189061/191649186-fcbd4c86-fcfe-4ae2-a870-71b42b8e7463.png)

account type: other
![image](https://user-images.githubusercontent.com/21189061/191649068-2dd32bce-1133-4586-9c69-cda391d1e6c2.png)
account type: loan
![image](https://user-images.githubusercontent.com/21189061/191649484-3e1d2aee-0469-47bb-ae3a-03756185ee33.png)

My customer feedback said that there are records in these two accounts, but I didn't find them. According to the plaid documentation, I guess that it may need to be replaced with "investments/transactions/get", so I want to give it a try. But I got this error "client is not authorized to access the following products: ["investments"]"
I want to understand why the data under these two accounts cannot be found, because the configuration ""PLAID_PRODUCTS": ["transactions"]"
Thank you very much for your reply, this problem has been bothering me for a week, my client is very anxious to see his transaction records...

**Comment by DaLiangLee** [comment]
![image](https://user-images.githubusercontent.com/21189061/191649186-fcbd4c86-fcfe-4ae2-a870-71b42b8e7463.png)

account type: other
![image](https://user-images.githubusercontent.com/21189061/191649068-2dd32bce-1133-4586-9c69-cda391d1e6c2.png)
account type: loan
![image](https://user-images.githubusercontent.com/21189061/191649484-3e1d2aee-0469-47bb-ae3a-03756185ee33.png)

My customer feedback said that there are records in these two accounts, but I didn't find them. According to the plaid documentation, I guess that it may need to be replaced with "investments/transactions/get", so I want to give it a try. But I got this error "client is not authorized to access the following products: ["investments"]"
I want to understand why the data under these two accounts cannot be found, because the configuration ""PLAID_PRODUCTS": ["transactions"]"
Thank you very much for your reply, this problem has been bothering me for a week, my client is very anxious to see his transaction records...

**Comment by DaLiangLee** [comment]
![image](https://user-images.githubusercontent.com/21189061/191651541-fad6d376-ae01-4409-bee8-740d1afdcde8.png)
Could it be the reason here? investment not included

**Comment by ghernandez-plaid** [comment]
> ![image](https://user-images.githubusercontent.com/21189061/191651541-fad6d376-ae01-4409-bee8-740d1afdcde8.png) Could it be the reason here? investment not included

Hi @DaLiangLee – That is correct. The `/transactions/get` endpoint is part of the Transactions product, while the `investments/transactions/get` endpoint is part of the Investments product. Based on your screenshots, it appears that client is currently only using the Transactions product, which allows access to a user's transaction history for depository type accounts such as checking and savings accounts, credit type accounts such as credit cards, and student loan accounts. For transaction history from investment accounts, use Plaid's [Investments](https://plaid.com/docs/investments/) product.

To use the Investments product, you'll need to first request access to it by [submitting a product access request Support ticket](https://dashboard.plaid.com/support/new/product-and-development/product-troubleshooting/request-product-access) explaining your use case. Once approved, you'll be able to use the Investments product to fetch transaction history from investment accounts. You would then update the array of products that you're initializing with like so:

```
"PLAID_PRODUCTS": ["transactions", "investments"]
```

**Comment by DaLiangLee** [comment]
@ghernandez-plaid  Yes, thank you very much. Yesterday, I have changed it to "["transactions", "investments"]", but nothing has changed. Do I need to re-acquire the access token (I saved it in the database)?

**Comment by phoenixy1** [comment]
For the record, you would need to go back through the link flow and re-acquire the token.
