### ISSUE TITLE
Is there a way to add more trace logging to the Plaid node api

### ISSUE THREAD

**Issue by berlinbrown** [plaid/plaid-node#542]
Is there a way to add more trace logging to the Plaid node api

If we want to see the full request/response.  Almost like curl verbose debugging, is there a way to do that

**Comment by ghernandez-plaid** [comment]
> Is there a way to add more trace logging to the Plaid node api
> 
> If we want to see the full request/response. Almost like curl verbose debugging, is there a way to do that

Hi @berlinbrown, thanks for reaching out! What specific information are you trying to see? The full response should be returned in the response object after calling an endpoint (i.e., `response.data`). The same can be done for [errors](https://github.com/plaid/plaid-node#error-handling). You can also do something like this if you want to get a little more granular:

```js
...
.catch((error) => {
      const err = error.response.data;

      // Indicates plaid API error
      console.error('/exchange token returned an error', {
        error_type: err.error_type,
        error_code: err.error_code,
        error_message: err.error_message,
        display_message: err.display_message,
        documentation_url: err.documentation_url,
        request_id: err.request_id,
      });
...
```

This ^ code snippet comes from [the second code snippet in this section](https://github.com/plaid/plaid-node#promise-support).

**Comment by berlinbrown** [comment]
This is fine,  I was hoping that there was a config setting within the library that would add more logging.  But this also works as well from axios.

But in general, almost like a proxy server, print the request, headers, response, headers, etc.


https://www.npmjs.com/package/axios-debug-log

**Comment by ghernandez-plaid** [comment]
> This is fine, I was hoping that there was a config setting within the library that would add more logging. But this also works as well from axios.
> 
> But in general, almost like a proxy server, print the request, headers, response, headers, etc.
> 
> https://www.npmjs.com/package/axios-debug-log

Ah, understood. Thanks for the feedback @berlinbrown , the client library currently doesn't support functionality like this, but I'm going to pass your feedback on to the team that maintains it.
