### ISSUE TITLE
Need help trying to use this For Laravel in PHP...

### ISSUE THREAD

**Issue by andrewdwallo** [plaid/plaid-node#543]
If I was going to try to use Plaid with Laravel Models, Migration Tables, etc. How would I go about using your package so that I can receive requests and render responses with plaid? I also wanted to know... How would I go about using your package with Plaid Link where a user can login with something like Jetstream and click on a button to use link and have all of their data come in through the user interface in tables for Models..? I am also planning on using Filament Admin for this... Sorry for all the questions but I am having a hard time trying to do this with Plaid and I am having a lot of errors in doing so...  Maybe I am just a noob or something but how do I actually go about using your package for laravel?... There are some community packages for PHP but I would rather use something like this because it is supported and most of the php packages arent descriptive at all on how to use them. I would really appreciate your help, and if anyone else in this community knows anything about my question and how to do this I would really appreciate your help as well... thanks!

**Comment by ghernandez-plaid** [comment]
> If I was going to try to use Plaid with Laravel Models, Migration Tables, etc. How would I go about using your package so that I can receive requests and render responses with plaid? I also wanted to know... How would I go about using your package with Plaid Link where a user can login with something like Jetstream and click on a button to use link and have all of their data come in through the user interface in tables for Models..? I am also planning on using Filament Admin for this... Sorry for all the questions but I am having a hard time trying to do this with Plaid and I am having a lot of errors in doing so... Maybe I am just a noob or something but how do I actually go about using your package for laravel?... There are some community packages for PHP but I would rather use something like this because it is supported and most of the php packages arent descriptive at all on how to use them. I would really appreciate your help, and if anyone else in this community knows anything about my question and how to do this I would really appreciate your help as well... thanks!

Hi @andrewdwallo, thanks for reaching out. Unfortunately, Plaid does not support an official PHP client library. You can find more information on official client libraries and community-supported libraries here: https://plaid.com/docs/api/libraries/. 

On that page, we list https://github.com/TomorrowIdeas/plaid-sdk-php as a community-supported PHP library. The README for plaid-sdk-php has some examples on how to use the library. I'd suggest opening an issue in that repository if you feel the README should be expanded.

As a heads up, just note that community libraries are not officially supported by Plaid. Plaid cannot provide assistance with using community libraries or guarantee that they will be kept up-to-date with all the changes needed to support the latest modifications to the Plaid API.

**Comment by andrewdwallo** [comment]
If I used this with Laravel Inertia would it work then?

**Comment by andrewdwallo** [comment]
And would it work with Vue.js or should I go with either react or nuxt, etc.?

**Comment by andrewdwallo** [comment]
Or would it be best to set up docker with a front end and backend?

**Comment by ghernandez-plaid** [comment]
Hi @andrewdwallo, for guidance on how to set up the PHP community library to work with your app, it'd be best to open an issue in that repo: https://github.com/TomorrowIdeas/plaid-sdk-php. Thank you!
