### ISSUE TITLE
Transfer Auth Request missing Idempotency_Key 

### ISSUE THREAD

**Issue by JohnMeisterWork** [plaid/plaid-node#552]
interface TransferAuthorizationCreateRequest is missing idempotency_key from the allowable inputs. I Believe there are a few options that are missing here.

https://plaid.com/docs/api/products/transfer/#transferauthorizationcreate

    "plaid": "^9.9.0",

**Comment by phoenixy1** [comment]
@JohnMeisterWork new fields are added to the client libraries as they are added to the API, version 9.x does not have these fields as it pre-dates their addition to the Plaid API -- can you try upgrading to the latest client library and see if that resolves the issue?

**Comment by JohnMeisterWork** [comment]
Thanks, I didn't realize I was 3 behind.
