### ISSUE TITLE
The TransferEventType has some inconsistencies,  lacks the 'settled' type

### ISSUE THREAD

**Issue by ngatiajim** [plaid/plaid-node#553]
I believe there are some inconsistencies with the documentation for the below Transfer Event Types:
 - Documentation: "settled, swept_settled" 
 - Interface: "reverse_swept"

...
"Possible values: pending, cancelled, failed, posted, **settled**, returned, swept, **swept_settled**, return_swept"

export declare enum TransferEventType {
    Pending = "pending",
    Cancelled = "cancelled",
    Failed = "failed",
    Posted = "posted",
    Returned = "returned",
    Swept = "swept",
    ReverseSwept = "**reverse_swept**",
    ReturnSwept = "return_swept"
}
...

**Comment by phoenixy1** [comment]
@ngatiajim it seems like you might be using an outdated version of the client libraries -- can you try updating to latest? I checked the api.d.ts file currently on master and it appears to have the correct values in it:

```
export declare enum TransferEventType {
    Pending = "pending",
    Cancelled = "cancelled",
    Failed = "failed",
    Posted = "posted",
    Settled = "settled",
    Returned = "returned",
    Swept = "swept",
    SweptSettled = "swept_settled",
    ReturnSwept = "return_swept"
}
```

**Comment by ngatiajim** [comment]
Confirmed. Thanks, the current version 12.0.0 has the valid values.
