### ISSUE TITLE
redirect_uri not working in sandbox oauth

### ISSUE THREAD

**Issue by amansrivastav-bytequests** [plaid/plaid-node#560]
redirect uri not working in sandbox oauth. I have already add in dashboard panel.

**Comment by phoenixy1** [comment]
can you explain more about what's happening? Can you share the code section that is not working as expected and explain what is happening and how it is different from the expected result?

**Comment by amansrivastav-bytequests** [comment]
const configuration = new Configuration({
    basePath: PlaidEnvironments.sandbox,
    baseOptions: {
      headers: {
        'PLAID-CLIENT-ID': CLIENT_ID,
        'PLAID-SECRET': SECRET,
        "Plaid-Version": "2020-09-14",
      },
    },
  });

const client = new PlaidApi(configuration);

const tokenResponse = await client.linkTokenCreate({
        user: {
             client_user_id: "unique_user_id"
        },
        client_name: "Insert Client name here",
        language: "en",
        products: ["auth"],
        country_codes: ["US"],
        redirect_uri: "http://localhost:3000/oauth.html",
        });

here is javascript code:-


`function finishOAuth() {


    const storedTokenData = localStorage.getItem("linkTokenData");
    console.log(`I retrieved ${storedTokenData} from local storage`);
    const linkTokenData = JSON.parse(storedTokenData);
  
    const handler = Plaid.create({
      token: linkTokenData.link_token,
      receivedRedirectUri: window.location.href,
      onSuccess: async (publicToken, metadata) => {
        console.log(
          `I have a public token: ${publicToken} I should exchange this`
        );
        
        await exchangeToken(publicToken); 
      },
      onExit: (err, metadata) => {
        console.log(
          `I'm all done. Error: ${JSON.stringify(err)} Metadata: ${JSON.stringify(
            metadata
          )}`
        );
        if (err !== null) {
          document.querySelector("#userMessage").innerHTML = "Oh no! We got some kind of error! Please <a href='/sales/application'>try again.</a>";
        }
      },
      onEvent: (eventName, metadata) => {
        console.log(`Event ${eventName}`);
      },
    });
    handler.open();
  }
finishOAuth();`

**Comment by phoenixy1** [comment]
Can you describe what happens when you try to link an OAuth institution, and what actually happens?

Also at a quick glance your original Link initialization code contains a receivedRedirectUri, it should not contain that, that should only be specified on re-initialization.

**Comment by amansrivastav-bytequests** [comment]
i am using sandbox enviroment. creating link token in above code sample. Link token is created successfully but its not redirect on mention redirect uri.

**Comment by phoenixy1** [comment]
@amansrivastav-bytequests can you check out the [tiny quickstart](https://github.com/plaid/tiny-quickstart) example code? This is code that we've verified correctly handles oauth redirects, so you should be able to work by tweaking it and comparing it to your codebase.

**Comment by amansrivastav-bytequests** [comment]
@phoenixy1  thanks for your response. Its really help me to solve this problem.
