### ISSUE TITLE
Where do you get public_token from?

### ISSUE THREAD

**Issue by anthonybudd** [plaid/plaid-node#566]
Where do you get `public_token` from? Why Isn't this documented?

As seen here: https://github.com/plaid/plaid-node#examples

**Comment by phoenixy1** [comment]
This is documented in the first line of the examples section linked, ("Exchange a public_token from [Plaid Link](https://plaid.com/docs/api#creating-items-with-plaid-link) for a Plaid access_token") although I do note that the link is broken, which is less than helpful. Thanks for pointing that out, I'll make sure to get it fixed.

The link should go here:

https://plaid.com/docs/link/

which has lots more information about Link and getting public tokens.

**Comment by phoenixy1** [comment]
I've merged a PR that fixes the broken link. It will be released with the next client library release.
