### ISSUE TITLE
Error thrown is not including all details in the response

### ISSUE THREAD

**Issue by mdesousa** [plaid/plaid-node#571]
Hi, we are following the steps here: https://www.npmjs.com/package/plaid#error-handling

However, it appears that the error object is missing the `error_message` from the response... see details in the ticket below.
https://dashboard.plaid.com/support/case/495160

Thanks

**Comment by phoenixy1** [comment]
Hmm...I was not able to reproduce this. Using the following code

```
  try {
  const transactionsResponse = await client.transactionsGet({ access_token: "not a real access token", start_date: '2022-01-01', end_date: '2023-01-01' });
  res.json({
    Transactions: transactionsResponse.data,
  });
} catch (error) {
  const err = error.response.data;
  console.error(err);
}
```

Results in the following being logged to the console:
```
{
  display_message: null,
  documentation_url: 'https://plaid.com/docs/?ref=error#invalid-input-errors',
  error_code: 'INVALID_ACCESS_TOKEN',
  error_message: 'provided access token is in an invalid format. expected format: access-<environment>-<identifier>',
  error_type: 'INVALID_INPUT',
  request_id: 'CBZ4nwFLgSULQvv',
  suggested_action: null
}
```

It seems possible that there may be an issue in how the error object is being captured in your implementation?
