### ISSUE TITLE
Missing endpoint

### ISSUE THREAD

**Issue by jeffreyflynt** [plaid/plaid-node#579]
I noticed this library is missing: `creditPayrollIncomeRiskSignalsGet` Would this be on the roadmap anytime soon?

**Comment by phoenixy1** [comment]
Are you're sure you're using the latest version of the library? The endpoint is defined here: https://github.com/plaid/plaid-node/blob/master/dist/api.d.ts#L7364

**Comment by jeffreyflynt** [comment]
Thanks, it didn't show up on Github search nor autocomplete in VSCode. Thanks.
