### ISSUE TITLE
Is the error handling code in the README correct ?

### ISSUE THREAD

**Issue by Ranhiru** [plaid/plaid-node#599]
Is this still valid ? 

https://github.com/plaid/plaid-node#error-handling

```typescript
try {
  await plaidClient.transactionsSync(request);
} catch (error) {
  const err = error.response.data;
}
```

That part of the README has not been updated for 2 years and it seems like that part is not up to date anymore. Can someone from Plaid chime in please ?

Thank you

**Comment by cgfarmer4** [comment]
Hi @Ranhiru -- yes, this is still the recommended error handling format. We have tests [here](https://github.com/plaid/plaid-node/blob/master/test/transactions.spec.ts#L42-L86) that show how this works more in depth.

Are you receiving something unexpected?

**Comment by Ranhiru** [comment]
@cgfarmer4 Thanks you. Are there type definitions for error ? Is it `PlaidError` ? Or is error.response.data is of type PlaidError ?

**Comment by cgfarmer4** [comment]
Error and response are Axios types but you are correct, `error.response.data` is of type `PlaidError`.

**Comment by Ranhiru** [comment]
Thank you :)
