### ISSUE TITLE
Bank Income verification doesn't trigger a webhook 

### ISSUE THREAD

**Issue by AxelRueda** [plaid/plaid-node#608]
Hi everyone,
I'm using this [guide](https://github.com/plaid/income-sample) and for some reason I'm not receiving any webhook when I finish the "bank income report process" through plaid widget.

If I use the same application / client and I test the "payroll income report process" through plaid widget. I receive a webhook like this one:

{
  "environment": "sandbox",
  "item_id": "DMVJD8yZr8SbPxGMJNGwu1e5PkMmo8fvyJVmP",
  "user_id": "f18d7876a7387bd147a90283c6df64530b8392144a75c9f50209217c60d32e36",
  "verification_status": "VERIFICATION_STATUS_PROCESSING_COMPLETE",
  "webhook_code": "INCOME_VERIFICATION",
  "webhook_type": "INCOME"
}

So if I'm not receiving the event, how do I know when the bank income report is ready to be consumed? Is this behaviour correct?

Thanks in advance

**Comment by phoenixy1** [comment]
This is as designed. Unlike Document Income, Bank Income does not fire a webhook, because it does not perform async processing.
