### ISSUE TITLE
Plaid open with specific institution instead of list

### ISSUE THREAD

**Issue by Abubakarraza** [plaid/plaid-node#616]
I use Plaid for connecting banks on the site and I have ui where I show the user all institutions using institution/get API and now I want which one institution user select Plaid only open with that institution instead of all. is it possible to achieve this?
Frontend:React js
Backend:Node js

**Comment by Abubakarraza** [comment]
@tokafish @miketaylr @HoyaBoya @stieg

**Comment by phoenixy1** [comment]
No, unfortunately Plaid doesn't support doing that.
