### ISSUE TITLE
How to get updated date with transaction list ?

### ISSUE THREAD

**Issue by hemangmehta** [plaid/plaid-node#62]
Hi,

I'm using getConnectUser() to get all transactions, It send me "date" field, which is created date i think,  I want updated date of transaction. Is there any way to get updated date along with created date?

**Comment by michaelckelly** [comment]
@hemangmehta - 

The `date` field on each transaction represents the date on which the transaction was posted by the financial institution.

**Comment by hemangmehta** [comment]
@michaelckelly do you mean financial institution provides only one date when transaction posted correct?
