### ISSUE TITLE
`RemovedTransaction.transaction_id` is optional

### ISSUE THREAD

**Issue by AlexLloyd0** [plaid/plaid-node#620]
The type definition for `RemovedTransaction` is 

```typescript
/**
 * A representation of a removed transaction
 * @export
 * @interface RemovedTransaction
 */
export interface RemovedTransaction {
    /**
     * The ID of the removed transaction.
     * @type {string}
     * @memberof RemovedTransaction
     */
    transaction_id?: string;
}
```

However the docs do not describe transaction_id as nullable:

<img width="613" alt="image" src="https://github.com/plaid/plaid-node/assets/14766017/7b32fe41-419e-45b1-9de3-268bc8aefc61">

This is inconsistent - do we have to handle `transaction_id === undefined`?

**Comment by phoenixy1** [comment]
Thanks for reporting, and sorry for the slow response! I think that's just an oversight in the OpenAPI file. `transaction_id` in this context should never be undefined.

**Comment by phoenixy1** [comment]
This has now been fixed; the fix will be available in the next client library release
