### ISSUE TITLE
Missing property on `LinkTokenCreateRequestAuth` interface

### ISSUE THREAD

**Issue by tomasmendes08** [plaid/plaid-node#627]
To implement text message verification to same day micro-deposits, we need to add `sms_microdeposits_verification_enabled` boolean to the `auth` object in `/link/token/create` configuration (as described in the screenshot from your [docs](https://plaid.com/docs/auth/coverage/same-day/#implementation-steps-1)).
![image](https://github.com/plaid/plaid-node/assets/56136112/da3b3684-b30d-40bb-9ecb-3f42cf435006)

However, I pulled your most recent release and I couldn't find the property in `LinkTokenCreateRequestAuth` interface. Your CHANGELOG here also didn't have any info about this.

Could you give me some insights on this matter, please?

**Comment by phoenixy1** [comment]
Can you make sure you're using the latest version of the Node client library (22.0)? The field should be present in that version.
