### ISSUE TITLE
statementsDownload returns corrupted PDF

### ISSUE THREAD

**Issue by danshapir** [plaid/plaid-node#629]
Calling the statementsDownload api will result in a corrupted PDF as you aren't adding:
```
{ responseType: 'arraybuffer' }
```

As part of the axios config, but returning a binary.

**Comment by phoenixy1** [comment]
@danshapir Thanks for the report! Do you have code that repros this? I tried using StatementsDownload in the Quickstart with node and it did download the PDF successfully. 

https://github.com/plaid/quickstart/blob/master/node/index.js#L460

**Comment by phoenixy1** [comment]
@danshapir Thanks for the report! To handle this, you will specify `{responseType: 'arraybuffer'}` during the call itself. An example of this is shown in the Quickstart:

https://github.com/plaid/quickstart/blob/master/node/index.js#L437

```
      const pdfResponse = await client.assetReportPdfGet(pdfRequest, {
        responseType: 'arraybuffer',
      });
```

**Comment by phoenixy1** [comment]
@danshapir This same pattern is used in the Quickstart and results in a non-corrupted PDF:

https://github.com/plaid/quickstart/blob/master/node/index.js#L460

```
      const statementsDownloadResponse = await client.statementsDownload(pdfRequest, {
        responseType: 'arraybuffer',
      });
```
