### ISSUE TITLE
Server-side implementation

### ISSUE THREAD

**Issue by CodyBontecou** [plaid/plaid-node#630]
Is it possible to create a fully-server-side implementation of Plaid, without a frontend to generate the Plaid link?

**Comment by phoenixy1** [comment]
Link is required; however, you can use Hosted Link, in which Plaid handles the front end for you:

https://plaid.com/docs/link/hosted-link/

**Comment by CodyBontecou** [comment]
Hmm, would hosted-link enable a cron-based workflow? I'm just trying to get a daily update on my balance.

**Comment by ToddKerpelman** [comment]
You would still need to use Link (or Hosted Link) to establish your user's connection to the bank. Once you've done that, though, you're free to make server-side calls to accounts/balance/get with whatever mechanism you'd like, including cron jobs.

**Comment by CodyBontecou** [comment]
Does the accessToken need to be refreshed? Or can I generate it once, store it in a database, and continue using it?

**Comment by phoenixy1** [comment]
access token documentation is here: https://plaid.com/docs/quickstart/glossary/#access-token

Closing out this thread as it is not directly related to the plaid-node library
