### ISSUE TITLE
Transaction amount digital counts (Not the same with bank statement)

### ISSUE THREAD

**Issue by smiley717** [plaid/plaid-node#637]
Hello,

We have found that Plaid rounds some large amounts. How many digits are being processed?

Are amounts rounded if they exceed 6 digits?

144575.57 -> 144575.6
124523.1 -> 124523
For instance, I have a transaction for Bank of America, 5304 on Jan 2.

MERCHANT SERVICE DES: XXXX

amount from Plaid: -16023.5
amount from bank statement: - 16023.47

We have found these issues for other accounts as well

**Comment by phoenixy1** [comment]
Hi! We're closing this out as this is not specific to the node library and requires account-specific information to troubleshoot, which can't be done securely over GitHub -- please file a support ticket for any help with this issue. Thanks!

**Comment by smiley717** [comment]
Thanks Alex, I have already submitted a ticket through Dashboard, but would like to hear an opinion from the developer's perspective. do you happen to know how long digits is Plaid handling?
