### ISSUE TITLE
No support for days_requested on plaid create token

### ISSUE THREAD

**Issue by mschunke** [plaid/plaid-node#640]
Hello, I'm using the Plaid-node SDK with Typescript and when trying to supply the `transactions/days_requested` value to the `.linkTokenCreate` function I can't find the types for the `transactions` property.

Sample code:
```
    const { data } = await plaid.linkTokenCreate({
      client_name: "Some client",
      country_codes: [CountryCode.Us],
      products: [Products.Transactions],
      language: "en",
      user: { client_user_id: request.auth.uid },
      // Using TS ignore as Plaid's SDK doesn't have types for this field
      // @ts-ignore
      transactions: {
        days_requested: 730,
      },
    });
```

Source documentation: [here](https://plaid.com/docs/api/tokens/#link-token-create-request-transactions)

**Comment by phoenixy1** [comment]
You're probably using an old version of the library. Upgrading to the latest version should fix it.
