### ISSUE TITLE
onExit not being called

### ISSUE THREAD

**Issue by MauriMiguez** [plaid/plaid-node#648]
We are using [Plaid's Flutter SDK](https://github.com/jorgefspereira/plaid_flutter) and we noticed that the onExit method was not being called. 

Initially we submitted an [issue](https://github.com/plaid/plaid-node/issues/new) on that repo but the author [@jorgefspereira](https://github.com/jorgefspereira) [pointed](https://github.com/jorgefspereira/plaid_flutter/issues/134#issuecomment-2402612075) that it may be a underlying issue with the Plaid SDK itself. 

**Here is a brief description of the issue:**
When triggering the flow to connect a bank account and closing it, it won't send the event of LinkExit. This only happens if the 'X' button is pressed immediately after the flow opens (without pressing 'continue'). However, if the 'X' is pressed after advancing in the flow, the event is emitted correctly.

One thing to keep in mind is that we are using version 3.1.8 of the Plaid's Flutter SDK.

Since the problem was only happening on the Web (not on iOS or Android) we decided to report the issue here. Let me know if this is the correct place.

**Comment by phoenixy1** [comment]
@MauriMiguez thanks for the report! I'm not able to reproduce this -- is there any chance you'd be able to provide a recording of the repro *without* the Flutter SDK involved?

**Comment by phoenixy1** [comment]
Closed due to inability to repro / lack of response.
