### ISSUE TITLE
Unable to fetch the transaction History

### ISSUE THREAD

**Issue by iprime2** [plaid/plaid-node#651]
I am unable to get transaction History for any accounts below it the error and code link

https://github.com/iprime2/banking-nextjs/blob/31278cf9fcfec5c46a913f2bce56b2e1f3c9c762/lib/actions/bank.actions.ts#L122

error : 
 data: {
      display_message: null,
      documentation_url: 'https://plaid.com/docs/?ref=error#invalid-input-errors',
      error_code: 'ADDITIONAL_CONSENT_REQUIRED',
      error_message: 'client does not have user consent to access the PRODUCT_TRANSACTIONS product',
      error_type: 'INVALID_INPUT',
      request_id: 'QJkPsrSbPqO5njq',
      suggested_action: null
    }
    
    
![image](https://github.com/user-attachments/assets/dbff205a-8165-4be5-ab94-539297997cad)

**Comment by phoenixy1** [comment]
Thank you for providing the error code details for this issue! The troubleshooting tips for this error are here https://plaid.com/docs/errors/invalid-input/#additional_consent_required and should explain how to resolve it. In this specific case, it looks like you need to include the transactions product in the /link/token/create call, or add it to existing Items via update mode.

Closing this issue as it appears to be unrelated to the Node client library. If the troubleshooting information provided above isn't sufficient to solve your problem, please go ahead and file a support ticket via the Dashboard.
