### ISSUE TITLE
`last_statement_balance` Missing From `StudentLoan` Interface

### ISSUE THREAD

**Issue by aditya-arcot** [plaid/plaid-node#653]
The `last_statement_balance` property is missing from the `StudentLoan` interface and the Liabilities API docs for the `liabilitiesGet` endpoint.
This field is returned as part of the student loan objects when the `liabilitiesGet` endpoint is called.

**Comment by phoenixy1** [comment]
@aditya-arcot Thank you for the report! This has been fixed in yesterday's release of the node client library.

**Comment by aditya-arcot** [comment]
Sounds good, thanks
