### ISSUE TITLE
Pending for wells fargo

### ISSUE THREAD

**Issue by ro31337** [plaid/plaid-node#70]
Here is my script to pull transactions from my wells fargo bank:

```javascript
var plaid = require('plaid');

var plaidClient = new plaid.Client('__removed__', '__removed__', plaid.environments.tartan);

var options = {};

plaidClient.addConnectUser('wells',
    {
        username: '__wells_username__',
        password: '__password_removed__',
    },
    options,
    function(err, mfaRes, response) {
        var token = response.access_token;

        plaidClient.getConnectUser(token,
            {
                pending: true, // <-- SPECIFIED
                account: response.accounts[0]._id,
                gte: '5 days ago',
            },
            function(err, response) {
                // console.dir(response);
                for(var i = 0; i < response.transactions.length; i++) {
                  var t = response.transactions[i];
                  console.log(t.date + '\t' + (t.amount * -1) + '\t\t' + t.name);
                }
            });
    });
```

I don't see any pending transactions.

This thing also doesn't work:

```sh
curl -X POST https://tartan.plaid.com/connect/get \
  -d client_id=__ID_REMOVED__ \
  -d secret=__SECRET_REMOVED__ \
  -d options='{"pending":true, "gte":"5 days ago"}' \
  -d account=__ACCOUNT_REMOVED__ \
  -d access_token=__TOKEN_REMOVED__
```

I've seen on GitHub that you ask customers to contact them by email. I'm not ready to give you my token. Feel free to go ahead and try it yourself. Wells Fargo is quite popular. I think it's something about Plaid.

Let me know and please don't close this issue (as similar other issues you've closed), until it's resolved. Thanks for help!

**Comment by jkantr** [comment]
So I had a similar issue to this a few months back, which I subsequently worked around.. somehow. It had to do with the original endpoint used to register the account (Auth vs. Connect) and then specifying pending here explicitly like you're doing. I'll try to check revisioning history and see if I can track it down again.

**Comment by whockey** [comment]
Hey @ro31337 co-founder of Plaid here - thanks for bringing this up! I just added my Wells Fargo account and everything seems to be working. We're more than happy to check out the issue - but you would have to email your `access_token` or account id to support@plaid.com.

**Comment by michaelckelly** [comment]
@ro31337 - It looks like we were able to resolve this via support@plaid.com! I'm going to go ahead and close this issue!

**Comment by ro31337** [comment]
Confirmed. Issue resolved, now it works!

**Comment by michaelckelly** [comment]
Thanks @ro31337 - let's keep that conversation there, I'm sure wen can get to the bottom of this shortly!

**Comment by ro31337** [comment]
Thanks, I'll update my comment here, because this is exactly what I needed to know about Plaid before using that. I invested my time already, so I think this information and my impressions can be useful for everyone.
