### ISSUE TITLE
Retrieve status of token?

### ISSUE THREAD

**Issue by jkantr** [plaid/plaid-node#71]
Is there an endpoint or otherwise some common method of confirming the 'state' of an account/token?

I've run into various situations now for instance where I would like to check the current products associated to see if an upgrade is needed, or to check what the current webhook is associated with this token.. those sorts if things.

**Comment by michaelckelly** [comment]
@jkantr -

There is not an API endpoint for this at this time. The [dashboard](https://dashboard.plaid.com) allows you to inspect an individual access token though. You can also update the webhook associated with a access token by making a PATCH API request (see https://plaid.com/docs/api/#update-connect-user).

Please direct these questions to support@plaid.com in future - we try to reserve this area for issues with the plaid-node library itself!
