### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by tyvdh** [plaid/plaid-node#72]
I'm trying to call the Plaid API from an Ionic app and getting a CORS error.
My guess is I need a self signed cert or some such thing. Can someone guide me into the best practice for both testing this (localhost, non https env) as well as production inside a hybrid app?

```
Fetch API cannot load https://tartan.plaid.com/connect/get. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.1.151:8100' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by michaelckelly** [comment]
@tyvdh - The `/connect/get` endpoint does not support CORS requests as doing so would require placing your client ID and secret within the app. Instead, we suggest you make the API request from a backend server. That is, your app can make a request to your server which will then make an authenticated Plaid API request.

**Comment by tyvdh** [comment]
Ah gotcha. Makes sense.
