### ISSUE TITLE
Update webhook (Patch) not working without creadential

### ISSUE THREAD

**Issue by hemangmehta** [plaid/plaid-node#73]
When i tried to do it,
```
plaidClient.patchConnectUser(access_token, {}, {
  webhook: 'http://requestb.in',
}, function(err, mfaResponse, response) {
  // The webhook URI should receive a code 4 "webhook acknowledged" webhook 
});
```

i got below error - 
```
{ code: 1200,
  message: 'invalid credentials',
  resolve: 'The username or password provided were not correct.',
  access_token: 'test_bofa',
  statusCode: 402 }
```

As per documentation i can call PATCH /connect without username/password. is there something missing in node lib. can any one help me out please.

**Comment by hemangmehta** [comment]
It's fixed for me now. it's not working for test accounts. suggestion : it should work for test account too. or change error message.

**Comment by Kluskey** [comment]
+1 this should work for test accounts too.

**Comment by G-Pandey** [comment]
I still get the above error message with test accounts. @hemangmehta can you help?

**Comment by hemangmehta** [comment]
@G-Pandey : Are you using same function `patchConnectUser()` ?. can you share more details about your case, because now i am not using this method to register webhook.

**Comment by chearmstrong** [comment]
Hi, I have the same issue when trying to register a webhook for a test account - is there a fix or a workaround for this?
