### ISSUE TITLE
plaidClient.exchangeToken method not returning stripe_bank_account_token

### ISSUE THREAD

**Issue by deepeshsunku** [plaid/plaid-node#74]
On my Plaid dashboard I have been approved for the Stripe ACH + Plaid Link integration and see the following message: You're approved to use Plaid Link to instantly tokenize your customers' bank accounts for use with Stripe's ACH API. Your Stripe account is linked! Check out a demo and then head to the docs to get started.

But when I try to use the exchangeToken method using the plaid-node library I only get a access_token back and not a stripe_bank_account_token. Below is my implementation. I'm using the sandbox environment.

`plaidClient.exchangeToken(public_token, account_id, function(err, response) {`
    `if (err != null) {`
     ` // Handle error!`
     ` console.log("PLAID exchange token error", err)`
    `} else {`
    `  // This is your Plaid access token - store somewhere persistent`
    `  // The access_token can be used to make Plaid API calls to`
    `  // retrieve accounts and transactions`
    `  var access_token = response.access_token;`
    `  var bank_account_token = response.stripe_bank_account_token;`
	`  console.log("PLAID ACCESS TOKEN and STRIPE TOKEN", access_token, bank_account_token)`
   ` }`
 ` });`

**Comment by deepeshsunku** [comment]
The reason I was not receiving the stripe token is because I wasn't using my public key on the client side, I was using the sandbox public key.

**Comment by sur** [comment]
@deepeshsunku are you able to generate the Stripe token for the "Sandbox" mode ?

**Comment by kamalcheema6** [comment]
I am also facing same issue.How to fix this?

**Comment by deepeshsunku** [comment]
@kamalcheema6 you need to use the public key provided to you on your Plaid Dashboard.
