### ISSUE TITLE
addAuthUser not working for American Express

### ISSUE THREAD

**Issue by nicholasalanbrown** [plaid/plaid-node#75]
I'm following the instructions to authorize a user on an American Express account but I get this response:

```
I20160714-16:25:44.128(-4)? { code: 1601,
I20160714-16:25:44.129(-4)?   message: 'product not available',
I20160714-16:25:44.129(-4)?   resolve: 'This product is not yet available for this institution.',
I20160714-16:25:44.129(-4)?   statusCode: 404 }
```

The documentation says American Express is supported - what gives?

Here's my code:

```
import plaid from 'plaid';
const plaidClient = new plaid.Client(myPlaidClientId, myPlaidSecrett, plaid.environments.tartan);

plaidClient.addAuthUser('amex', {username: 'myUsername', password: 'myPassword'}, function (error, response) {
  if (error) {
    console.log(error);
  }
  else {
    console.log(response);
  }
);
```

**Comment by blwinters** [comment]
Perhaps they updated the documentation since you posted this, but currently the ["Institutions by product" table](https://plaid.com/docs/api/#institution-overview) says that Amex is not supported for Auth.

**Comment by michaelckelly** [comment]
@nicholasalanbrown - Apologies for the slow response on this issue. @blwinters is correct (thanks!) - Plaid does not support the Auth product for American Express. 

The  ["Institutions by product" table](https://plaid.com/docs/api/#institution-overview) table your best resource there.

**Comment by michaelckelly** [comment]
Going to close this issue for now - @nicholasalanbrown please reopen if needed.

**Comment by juliagabrielle** [comment]
Hi Michael - has there been any effort to work on or fix this issue? I see that AMEX is still not supported, but I'm looking to understand if there is a workaround that Plaid offers so that all of our users who used to use American Express (Amex) as their institution can still link their accounts with Auth. Please let me know if there's a fix! Thank you.
