### ISSUE TITLE
remove `body` from GET unauthenticated requests

### ISSUE THREAD

**Issue by michaelckelly** [plaid/plaid-node#78]

**Comment by beshkenadze** [comment]
Here is PR https://github.com/plaid/plaid-node/pull/77

**Comment by beshkenadze** [comment]
23 days ago...c'mon Plaid team!

**Comment by nss213** [comment]
Today I'm seeing these requests failing with a 504. Removing the body seems to fix them.

**Comment by michaelckelly** [comment]
@nss213 @beshkenadze 

I apologize for the slow fix here and thank you both for your patience and willingness to put together a PR - it's much appreciated. The issue was due to server settings put in place against our development API environment (https://tartan.plaid.com).

**Comment by michaelckelly** [comment]
@nss213 @beshkenadze - fix published as `plaid@1.1.0`.
