### ISSUE TITLE
How would you submit a webhook update with the PATCH request?

### ISSUE THREAD

**Issue by tyvdh** [plaid/plaid-node#79]
There doesn't seem to be a way to submit a webhook update via the `patchConnectUser` method without including the credentials. The official Plaid documentation would suggest this is possible.

```
PATCH may also be used to update the webhook associated with a particular user. A PATCH request submitted without credentials but with a webhook will trigger a confirmation webhook.
```

**Comment by michaelckelly** [comment]
@tyvdh - Provide `null` as the argument value for `credentials`. Let
