### ISSUE TITLE
Can't make any requests

### ISSUE THREAD

**Issue by sean-hill** [plaid/plaid-node#83]
Hey there,

This isn't an issue with this library I believe, but the internal `request` library isn't returning any data from your endpoints. I'm calling `plaid.getInstitutions()` which internally is calling:

	REQUEST: 
		{ 
			uri: 'https://tartan.plaid.com/institutions',
			method: 'GET',
			body: {} 
		}

After 60 seconds it times out and returns nothing.

If you go to `https://tartan.plaid.com/institutions` the response is correct. So I'm just curious where the hangup is.

**Comment by michaelckelly** [comment]
@sean-hill - what version of the library are you using? You may be affected by https://github.com/plaid/plaid-node/issues/78.

Can you try with version `1.1.0` of the library?

**Comment by sean-hill** [comment]
@michaelckelly that did the trick! Thanks.

**Comment by michaelckelly** [comment]
Great, glad it worked @sean-hill
