### ISSUE TITLE
TypeScript typings

### ISSUE THREAD

**Issue by ralekna** [plaid/plaid-node#92]
Hi,

I wanted to ask if there exist TypeScript definitions for plaid-node client and how to install them if they exist.

Thanks!

**Comment by michaelckelly** [comment]
@ralekna - Thanks for reaching out. We don't have TypeScript definitions available currently -- if that's something you've put together independently, though, we'd love to incorporate them here for other developers.

**Comment by ralekna** [comment]
Hi @michaelckelly, 
I'll controbute them as soon as I finish them.

**Comment by QuentinFchx** [comment]
I've done the following for the client script. Might be inaccurate/incomplete (string/number confusion) but it's a start for anyone willing to use Plaid + TS in browsers.

```ts
interface PlaidObj {
    open(): void;
    exit(opts?: {force: boolean}): void;
}

interface PlaidInstitution {
    name: string;
    type: string;
}

interface PlaidAccount {
    id: string;
    name: string;
}

interface PlaidMetadata {
    institution?: PlaidInstitution;
    account?: PlaidAccount;
    account_id?: string;
}

interface PlaidOptions {
    clientName: string;
    product: 'auth' | 'connect' | 'info' | 'risk' | 'income';
    key: string;
    env: 'tartan' | 'production';
    onSuccess: (publicToken: string, metaData: PlaidMetadata) => void;
    onExit?: (error: any, metaData: any) => void;
    onLoad?: () => void;
    webhook?: string;
    token?: string;
    selectAccount?: boolean;
    isWebview?: boolean;
}

interface PlaidStatic {
    create(opts: PlaidOptions): PlaidObj;
    publishableKey: string;
}
```

**Comment by teledemic** [comment]
Having type definitions (for the server-side calls) either integrated or up on @typings would be extremely useful.

**Comment by michaelckelly** [comment]
@QuentinFchx - Thanks for contributing those! We recently released version 2 of this library for [Plaid's updated API](https://blog.plaid.com/improving-our-api/) but we've mirrored the legacy library at https://github.com/plaid/plaid-node-legacy

@teledemic @ralekna - I'll keep this issue for v2 of this library. The new API has more consistent response schemas, so it should be simpler to write the definitions.

**Comment by Tommyjohn05** [comment]
Can we get an update on this? I'm trying to implement Plaid into an Ionic 2 project.

Would really like to know the status of Typescript support.

**Comment by michaelckelly** [comment]
@Tommyjohn05 - We don't have official Typescript bindings yet. Happy to review a PR to incorporate those or help answer questions on that front.

**Comment by ralekna** [comment]
I created typings for legacy client but I think it can be easily converted to new client.
