### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by jjduhamel** [plaid/plaid-node#97]
I'm seeing this error periodically since upgrading to 1.2.0.

![image](https://cloud.githubusercontent.com/assets/1498326/22263430/4b684f9a-e229-11e6-958f-a5ad94cd1076.png)

**Comment by michaelckelly** [comment]
@jjduhamel - Do you have an example request that repros this?

**Comment by jjduhamel** [comment]
I filed a support ticket with information that will be helpful for debugging.

**Comment by michaelckelly** [comment]
@jjduhamel - This was addressed in https://github.com/plaid/plaid-node/pull/104 but the PR will need to be transitioned to [plaid-node-legacy](https://github.com/plaid/plaid-node-legacy).

**Comment by todoubled** [comment]
The new PR is up at https://github.com/plaid/plaid-node-legacy/pull/3
