### ISSUE TITLE
Return request id as requestId (camel-case) instead of request_id

### ISSUE THREAD

**Issue by jjduhamel** [plaid/plaid-node#98]
First, thanks for adding this!

It would be slightly better from my perspective if you converted request_id to camel-case, as you do with statusCode.  We're referencing this in our code in a few places, and it's annoying to have to keep track of different naming conventions for variables in the same module.

**Comment by michaelckelly** [comment]
Thanks @jjduhamel - this is no longer relevant for this library (Plaid's updated API returns as `request_id`. All fields are snake case now!

We can port this issue to [plaid-node-legacy](https://github.com/plaid/plaid-node-legacy) though!
